<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Exceptions &mdash; Plone Community Managed Developer Manual v1.0 documentation</title>
    <link rel="stylesheet" href="../_static/plone.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '1.0',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="top" title="Plone Community Managed Developer Manual v1.0 documentation" href="../index.html" />
    <link rel="up" title="Troubleshooting" href="index.html" />
    <link rel="next" title="Image troubleshooting" href="images.html" />
    <link rel="prev" title="Unicode encoding and decoding" href="unicode.html" />
<script language="javascript">
//<![CDATA[

Documentation.addTranslations({"locale": "fr", "plural_expr": "(n > 1)", "messages": {"See the definition": "Voir la d\u00e9finition"}});

// See http://disqus.disqus.com/general_integration_help/
var disqus_developer = 1;
if (document.location.protocol == 'http:') {
    disqus_developer = 0;
}

// Some HTML/CSS transforms we can't do in pure CSS (waiting for CSS3 support)
$(document).ready(function () {

    // Style of .. verisonmodified:: , .. versionadded:: ...
    $('p:has(span.versionmodified)').addClass('p-versionmodified');

    // Style of the TOC tree
    $('ul:has(li.toctree-l1)').addClass('toctree');

    // Decorate links to other sites
    $('a[class~=external]').attr('target', '_blank');

    // Glossary terms
    $('em.xref').attr('title', _('See the definition'));

    // We need to have all <pre> in a <div class="highlight"> to mimic pygments
    // to work around a pygments (?) bug
    var suffixes = {cfg: null, python:null};
    for (var suffix in suffixes) {
        var pattern = 'div.highlight-' + suffix + ' > pre';
        $(pattern).wrap('<div class="highlight" />');
    }
    return true;
});
//]]>
</script>

  </head>
  <body>
<!--[if lte IE 6]>
<style type="text/css">
#ie6msg{border:3px solid #090; margin:8px 0; background:#cfc; color:#000;}
#ie6msg h4{margin:8px; padding:0;}
#ie6msg p{margin:8px; padding:0;}
#ie6msg p a.getie8{font-weight:bold; color:#006;}
#ie6msg p a.ie6expl{font-weight:normal; color:#006;}
</style>
<div id="ie6msg">
<h4>Did you know that your browser is out of date?</h4>
<p>If the layout of this site seems ugly, that's because you're actually using
an outdated browser. And we wont put any effort to provide a nice layout to IE6
users.</p>
<p>To get the best possible experience using our website we recommend that you
upgrade your browser to a newer version. The current version
is <a class="getie8"
href="http://upgradeie.s3.amazonaws.com/eng/index.html">Internet Explorer
8</a>. The upgrade is free. If you're using a PC at work you should contact your
IT administrator.</p>
<p>If you want to you may also try some other popular Internet browsers
like <a class="ie6expl"
href="http://getfirefox.com">Firefox</a>, <a class="ie6expl"
href="http://www.google.com/chrome">Chrome</a>, <a class="ie6expl"
href="http://www.opera.com">Opera</a>, or <a class="ie6expl"
href="http://www.apple.com/safari/download/">Safari</a></p>
</div>
<![endif]-->

    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="images.html" title="Image troubleshooting"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="unicode.html" title="Unicode encoding and decoding"
             accesskey="P">previous</a> |</li>
        <li><a href="../index.html">Plone Community Managed Developer Manual v1.0 documentation</a> &raquo;</li>
          <li><a href="index.html" accesskey="U">Troubleshooting</a> &raquo;</li> 
      </ul>
    </div>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <div class="sphinx-content">
    <div class="section" id="exceptions">
<h1>Exceptions<a class="headerlink" href="#exceptions" title="Permalink to this headline">Â¶</a></h1>
<div class="admonition-description admonition ">
<p class="first admonition-title">Description</p>
<p class="last">Common exception traceback patterns developers might encounter with Plone.</p>
</div>
<p>List of common developer errors you might encounter and solutions for them.</p>
<div class="contents local topic" id="contents">
<ul class="simple">
<li><a class="reference internal" href="#attributeerror-str-object-has-no-attribute-other-mixed-zope-viewpagetemplate-and-five-viewpagetemplate" id="id1">AttributeError: 'str' object has no attribute 'other' (Mixed zope.viewpagetemplate and Five.viewpagetemplate)</a></li>
<li><a class="reference internal" href="#iteration-over-non-sequence-in-normalizeargs" id="id2">Iteration over non-sequence in _normalizeargs</a><ul>
<li><a class="reference internal" href="#case-1" id="id3">Case 1</a></li>
<li><a class="reference internal" href="#case-2" id="id4">Case 2</a></li>
</ul>
</li>
<li><a class="reference internal" href="#traversalerror-with-lots-of-tuples-and-lists-metal-problem" id="id5">TraversalError with lots of tuples and lists (METAL problem)</a></li>
<li><a class="reference internal" href="#attributeerror-in-setroles-due-to-workflow-state-transition" id="id6">AttributeError in setRoles due to workflow state transition</a></li>
<li><a class="reference internal" href="#add-on-installer-error-too-many-values-to-unpack" id="id7">Add-on installer error: too many values to unpack</a></li>
<li><a class="reference internal" href="#add-on-installer-error-this-object-was-originally-created-by-a-product-that-is-no-longer-installed" id="id8">Add-on installer error: This object was originally created by a product that is no longer installed</a></li>
<li><a class="reference internal" href="#z3c-form-based-form-updatewidgets-raises-componentlookuperror" id="id9">z3c.form based form updateWidgets() raises ComponentLookupError</a></li>
<li><a class="reference internal" href="#notfound-error-page-not-found-when-accessing-manage-portlets" id="id10">NotFound error (Page not found) when accessing &#64;&#64;manage-portlets</a><ul>
<li><a class="reference internal" href="#manually-removing-the-portlet" id="id11">Manually removing the portlet</a></li>
</ul>
</li>
<li><a class="reference internal" href="#attributeerror-getphysicalpath" id="id12">AttributeError: getPhysicalPath()</a><ul>
<li><a class="reference internal" href="#demostration" id="id13">Demostration</a></li>
</ul>
</li>
<li><a class="reference internal" href="#runtimeerror-maximum-recursion-depth-exceeded-archetypes-field-problem" id="id14">RuntimeError: maximum recursion depth exceeded (Archetypes field problem)</a></li>
<li><a class="reference internal" href="#invalid-or-duplicate-property-id" id="id15">Invalid or Duplicate property id</a></li>
<li><a class="reference internal" href="#traversalerror-no-traversable-adapter-found" id="id16">TraversalError: No traversable adapter found</a></li>
<li><a class="reference internal" href="#importerror-inappropriate-file-type-for-dynamic-loading" id="id17">ImportError: Inappropriate file type for dynamic loading</a></li>
<li><a class="reference internal" href="#badrequest-the-id-xxx-is-invalid-it-is-already-in-use" id="id18">BadRequest: The id &quot;xxx&quot; is invalid - it is already in use.</a></li>
<li><a class="reference internal" href="#exception-type-name-not-specified-in-createobject" id="id19">Exception: Type name not specified in createObject</a></li>
<li><a class="reference internal" href="#unauthorized-the-object-is-marked-as-private" id="id20">Unauthorized: The object is marked as private</a></li>
<li><a class="reference internal" href="#importerror-no-module-named-pil" id="id21">ImportError: No module named PIL</a></li>
<li><a class="reference internal" href="#notfound-while-accessing-a-browserview-based-view" id="id22">NotFound while accessing a BrowserView based view</a></li>
<li><a class="reference internal" href="#contentproviderlookuperror-plone-htmlhead" id="id23">ContentProviderLookupError: plone.htmlhead</a></li>
<li><a class="reference internal" href="#error-while-installing-a-new-portlet-portlets-xml-unbound-prefix" id="id24">Error while installing a new portlet portlets.xml: unbound prefix</a></li>
<li><a class="reference internal" href="#importerror-couldn-t-import-zpublishereventsbackport" id="id25">ImportError: Couldn't import ZPublisherEventsBackport</a></li>
<li><a class="reference internal" href="#error-zodb-connection-couldn-t-load-state-for-0x00" id="id26">ERROR ZODB.Connection Couldn't load state for 0x00</a></li>
<li><a class="reference internal" href="#poskeyerror" id="id27">POSKeyError</a></li>
<li><a class="reference internal" href="#zope-suddenly-dies-on-osx-without-a-reason" id="id28">Zope suddenly dies on OSX without a reason</a></li>
<li><a class="reference internal" href="#ioerror-errno-url-error-unknown-url-type-https" id="id29">IOError: [Errno url error] unknown url type: 'https'</a></li>
<li><a class="reference internal" href="#typeerror-len-of-unsized-object-in-smtplib" id="id30">TypeError: len() of unsized object in smtplib</a></li>
<li><a class="reference internal" href="#nameerror-name-test-is-not-defined" id="id31">NameError: name 'test' is not defined</a></li>
<li><a class="reference internal" href="#traversalerror-subject-name-in-expressions" id="id32">TraversalError(subject, name) in expressions</a></li>
<li><a class="reference internal" href="#content-status-history-won-t-render-traceback-is-content-path-reversed" id="id33">Content status history won't render - traceback is content path reversed</a></li>
<li><a class="reference internal" href="#attributeerror-module-object-has-no-attribute-httpsconnection" id="id34">AttributeError: 'module' object has no attribute 'HTTPSConnection'</a></li>
<li><a class="reference internal" href="#linguaplone-importerror-cannot-import-name-permissions" id="id35">LinguaPlone: ImportError: cannot import name permissions</a></li>
<li><a class="reference internal" href="#typeerror-nonetype-object-is-not-callable" id="id36">TypeError: 'NoneType' object is not callable</a></li>
<li><a class="reference internal" href="#importerror-no-module-named-pkgutil" id="id37">ImportError: No module named pkgutil</a></li>
<li><a class="reference internal" href="#picklingerror-can-t-pickle-class-collective-singing-async-iqueue-import-of-module-collective-singing-async" id="id38">&quot;PicklingError: Can't pickle &lt;class 'collective.singing.async.IQueue'&gt;: import of module collective.singing.async&quot;</a></li>
<li><a class="reference internal" href="#system-lxml-too-old" id="id39">System lxml too old</a></li>
<li><a class="reference internal" href="#traversalerror-standard-macros" id="id40">TraversalError: &#64;&#64;standard_macros</a></li>
<li><a class="reference internal" href="#attributeerror-wrapper-descriptor-object-has-no-attribute-im-func" id="id41">AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'</a></li>
<li><a class="reference internal" href="#getutility-fails-componentlookuperror" id="id42">getUtility() fails: ComponentLookupError</a></li>
<li><a class="reference internal" href="#attributeerror-request-in-getobject" id="id43">AttributeError: REQUEST in getObject</a></li>
<li><a class="reference internal" href="#get-language-nonetype-object-has-no-attribute-getlocaleid" id="id44">get_language: 'NoneType' object has no attribute 'getLocaleID'</a></li>
<li><a class="reference internal" href="#error-restore-index-when-starting-instance-zeo-server" id="id45">Error _restore_index() when starting instance / ZEO server</a></li>
<li><a class="reference internal" href="#importtoolset-typeerror-nonetype-object-is-not-callable" id="id46">importToolset: TypeError: 'NoneType' object is not callable</a></li>
<li><a class="reference internal" href="#from-zopeskel-basic-namespace-import-basicnamespace" id="id47">from zopeskel.basic_namespace import BasicNamespace</a></li>
<li><a class="reference internal" href="#extensionclass-extensionclass-object-is-not-iterable" id="id48">'ExtensionClass.ExtensionClass' object is not iterable</a></li>
</ul>
</div>
<div class="section" id="attributeerror-str-object-has-no-attribute-other-mixed-zope-viewpagetemplate-and-five-viewpagetemplate">
<h2><a class="toc-backref" href="#id1">AttributeError: 'str' object has no attribute 'other' (Mixed zope.viewpagetemplate and Five.viewpagetemplate)</a><a class="headerlink" href="#attributeerror-str-object-has-no-attribute-other-mixed-zope-viewpagetemplate-and-five-viewpagetemplate" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/moo/sits/src/plone.z3cform/plone/z3cform/crud/crud-master.pt
   - Line 17, Column 2
   - Expression: &lt;PathExpr standard:u'form/render'&gt;
   - Names:
      {'args': (),
       'context': &lt;SitsPatient at /folder_sits/sitsngta/intranet/sitsdatabase/sitscountry_TE/sitshospital_TES/sitspatient.TETES2009062217&gt;,
       'default': &lt;object object at 0xb7d76538&gt;,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': {},
       'request': &lt;HTTPRequest, URL=http://localhost:9000/folder_sits/sitsngta/intranet/sitsdatabase/sitscountry_TE/sitshospital_TES/sitspatient.TETES2009062217/@@ar&gt;,
       'template': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewPageTemplateFile object at 0xc6e552c&gt;,
       'usage': &lt;zope.pagetemplate.pagetemplate.TemplateUsage object at 0xf7fb78c&gt;,
       'view': &lt;Products.SitsPatient.browser.ar.ARCrudForm object at 0xf928ccc&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0xf7b4a0c&gt;}
  Module Products.PTProfiler.ProfilerPatch, line 32, in __patched_call__
  Module zope.tales.expressions, line 217, in __call__
  Module zope.tales.expressions, line 211, in _eval
  Module z3c.form.form, line 143, in render
  Module Shared.DC.Scripts.Bindings, line 313, in __call__
  Module Shared.DC.Scripts.Bindings, line 348, in _bindAndExec
  Module Shared.DC.Scripts.Bindings, line 1, in ?
  Module Shared.DC.Scripts.Bindings, line 293, in _getTraverseSubpath
AttributeError: 'str' object has no attribute 'other'</pre>
</div>
<p>Five ViewPageTemplate class file is slightly different than Zope 3's normal ViewPageTemplate file.
In this case Five ViewPageTemplate was used, when Zope 3's normal ViewPageTemplate was expected.</p>
<p>Another reason is that acquisition chain is not properly set-up in your custom views.</p>
<p>Difference:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">from</span> <span class="nn">Products.Five.browser.pagetemplatefile</span> <span class="kn">import</span> <span class="n">ViewPageTemplateFile</span>
</pre></div>
</div>
<p>vs.</p>
</div>
<div class="section" id="iteration-over-non-sequence-in-normalizeargs">
<h2><a class="toc-backref" href="#id2">Iteration over non-sequence in _normalizeargs</a><a class="headerlink" href="#iteration-over-non-sequence-in-normalizeargs" title="Permalink to this headline">Â¶</a></h2>
<div class="section" id="case-1">
<h3><a class="toc-backref" href="#id3">Case 1</a><a class="headerlink" href="#case-1" title="Permalink to this headline">Â¶</a></h3>
<p>The following log trace will appear when you try to render
the site, but you can access ZMI normally:</p>
<div class="highlight-python"><pre>2009-09-23 20:47:18 WARNING OFS.Uninstalled Could not import class 'IPloneCommentsLayer' from module 'quintagroup.plonecomments.interfaces'
2009-09-23 20:47:18 ERROR Zope.SiteErrorLog 1253728038.160.534632167217 http://localhost:9444/XXX
Traceback (innermost last):
  Module plone.postpublicationhook.hook, line 65, in publish
  Module ZPublisher.BaseRequest, line 424, in traverse
  Module ZPublisher.BeforeTraverse, line 99, in __call__
  Module Products.CMFCore.PortalObject, line 94, in __before_publishing_traverse__
  Module zope.event, line 23, in notify
  Module zope.component.event, line 26, in dispatch
  Module zope.component._api, line 130, in subscribers
  Module zope.component.registry, line 290, in subscribers
  Module zope.interface.adapter, line 535, in subscribers
  Module zope.component.event, line 33, in objectEventNotify
  Module zope.component._api, line 130, in subscribers
  Module zope.component.registry, line 290, in subscribers
  Module zope.interface.adapter, line 535, in subscribers
  Module plone.browserlayer.layer, line 18, in mark_layer
  Module zope.interface.declarations, line 848, in directlyProvides
  Module zope.interface.declarations, line 1371, in _normalizeargs
  Module zope.interface.declarations, line 1370, in _normalizeargs
TypeError: iteration over non-sequence
2009-09-23 20:47:18 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/home/moo/XXX/parts/zope2/lib/python/OFS/SimpleItem.py", line 227, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/moo/workspace2/collective.skinny/collective/skinny/patch.py", line 8, in standard_error_message
    return self.restrictedTraverse('@@404.html')()
  File "/home/moo/workspace2/collective.skinny/collective/skinny/fourohfour.py", line 22, in __call__
    return skins.plone_templates.standard_error_message.__of__(
  File "/home/moo/XXX/eggs/Products.CMFCore-2.1.2-py2.4.egg/Products/CMFCore/FSPythonScript.py", line 140, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/moo/XXX/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 313, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/moo/XXX/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 350, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/moo/XXX/eggs/Products.CMFCore-2.1.2-py2.4.egg/Products/CMFCore/FSPythonScript.py", line 196, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 27, in standard_error_message
AttributeError: default_error_message</pre>
</div>
<p>This usually means that you have copied Data.fs from another
system, but you do not have identical add-on product configuration
installed.</p>
<p><a class="reference external" href="http://plone.org/documentation/error/typeerror-iteration-over-non-sequence">For more info see this error reference on plone.org</a>.</p>
</div>
<div class="section" id="case-2">
<h3><a class="toc-backref" href="#id4">Case 2</a><a class="headerlink" href="#case-2" title="Permalink to this headline">Â¶</a></h3>
<p>Example traceback:</p>
<div class="highlight-python"><pre>Traceback (most recent call last):
  File "/home/moo/twinapex/bin/idelauncher.py", line 158, in ?
    execfile(ZOPE_RUN)
  File "/home/moo/twinapex/bin/../parts/zope2/lib/python/Zope2/Startup/run.py", line 56, in ?
    run()
  File "/home/moo/twinapex/bin/../parts/zope2/lib/python/Zope2/Startup/run.py", line 21, in run
    starter.prepare()
  File "/home/moo/twinapex/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 102, in prepare
    self.startZope()
  File "/home/moo/twinapex/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 278, in startZope
    Zope2.startup()
  File "/home/moo/twinapex/parts/zope2/lib/python/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/moo/twinapex/parts/zope2/lib/python/Zope2/App/startup.py", line 45, in startup
    OFS.Application.import_products()
  File "/home/moo/twinapex/parts/zope2/lib/python/OFS/Application.py", line 686, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/home/moo/twinapex/parts/zope2/lib/python/OFS/Application.py", line 709, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/moo/twinapex/eggs/Products.PloneHelpCenter-4.0a1-py2.4.egg/Products/PloneHelpCenter/__init__.py", line 9, in ?
    from Products.PloneHelpCenter import content
  File "/home/moo/twinapex/eggs/Products.PloneHelpCenter-4.0a1-py2.4.egg/Products/PloneHelpCenter/content/__init__.py", line 10, in ?
    import HowToFolder, HowTo
  File "/home/moo/twinapex/eggs/Products.PloneHelpCenter-4.0a1-py2.4.egg/Products/PloneHelpCenter/content/HowTo.py", line 40, in ?
    class HelpCenterHowTo(PHCContentMixin, ATCTOrderedFolder):
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/interface/advice.py", line 132, in advise
    return callback(newClass)
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/interface/declarations.py", line 485, in _implements_advice
    classImplements(cls, *interfaces)
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/interface/declarations.py", line 462, in classImplements
    spec.declared += tuple(_normalizeargs(interfaces))
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/interface/declarations.py", line 1372, in _normalizeargs
    _normalizeargs(v, output)
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/interface/declarations.py", line 1371, in _normalizeargs
    for v in sequence:
TypeError: iteration over non-sequence</pre>
</div>
<p>Reason: You are trying to use Plone 4 (Zope 2.12) add-on on Plone 3 (Zope 2.10). Zope interface declarations have been changed.</p>
<p><strong>Solution 1</strong>: Pick the older version for the add-on which is known to work with Plone 3. Make sure that you
delete all &quot;too eggs&quot; from <tt class="docutils literal"><span class="pre">eggs/</span></tt> and <tt class="docutils literal"><span class="pre">src/</span></tt> folders.</p>
<p><strong>Solution 2</strong>: Upgrade your site to Plone.</p>
</div>
</div>
<div class="section" id="traversalerror-with-lots-of-tuples-and-lists-metal-problem">
<h2><a class="toc-backref" href="#id5">TraversalError with lots of tuples and lists (METAL problem)</a><a class="headerlink" href="#traversalerror-with-lots-of-tuples-and-lists-metal-problem" title="Permalink to this headline">Â¶</a></h2>
<p>Exception:</p>
<div class="highlight-python"><pre>  File "/home/moo/yourinstance/parts/zope2/lib/python/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/home/moo/yourinstance/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 155, in _eval
    ob = self._subexprs[-1](econtext)
  File "/home/moo/yourinstance/parts/zope2/lib/python/zope/tales/expressions.py", line 124, in _eval
    ob = self._traverser(ob, element, econtext)
  File "/home/moo/yourinstance/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 85, in boboAwareZopeTraverse
    request=request)
  File "/home/moo/yourinstance/parts/zope2/lib/python/zope/traversing/adapters.py", line 164, in traversePathElement
    return traversable.traverse(nm, further_path)
   - __traceback_info__: ({u'main': [('version', '1.6'), ('mode', 'html'), ('setPosition', (7, 0)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('beginScope', {u'define-macro': u'main'}), ('optTag', (u'metal:main-macro', None, 'metal', 0, [('startTag', (u'metal:main-macro', [(u'define-macro', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1)), ('setPosition', (8, 1)), ('defineSlot', (u'main', [('beginScope', {u'define-slot': u'main'}), ('optTag', (u'metal:main-slot', None, 'metal', 0, [('startTag', (u'metal:main-slot', [(u'define-slot', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1))])), ('endScope', ())])), ('setPosition', (9, 1)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('rawtextColumn', (u'\n', 0))])), ('endScope', ())]}, 'master')
  File "/home/moo/yourinstance/parts/zope2/lib/python/zope/traversing/adapters.py", line 52, in traverse
    raise TraversalError(subject, name)
   - __traceback_info__: ({u'main': [('version', '1.6'), ('mode', 'html'), ('setPosition', (7, 0)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('beginScope', {u'define-macro': u'main'}), ('optTag', (u'metal:main-macro', None, 'metal', 0, [('startTag', (u'metal:main-macro', [(u'define-macro', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1)), ('setPosition', (8, 1)), ('defineSlot', (u'main', [('beginScope', {u'define-slot': u'main'}), ('optTag', (u'metal:main-slot', None, 'metal', 0, [('startTag', (u'metal:main-slot', [(u'define-slot', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1))])), ('endScope', ())])), ('setPosition', (9, 1)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('rawtextColumn', (u'\n', 0))])), ('endScope', ())]}, 'master', [])
TraversalError: ({u'main': [('version', '1.6'), ('mode', 'html'), ('setPosition', (7, 0)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('beginScope', {u'define-macro': u'main'}), ('optTag', (u'metal:main-macro', None, 'metal', 0, [('startTag', (u'metal:main-macro', [(u'define-macro', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1)), ('setPosition', (8, 1)), ('defineSlot', (u'main', [('beginScope', {u'define-slot': u'main'}), ('optTag', (u'metal:main-slot', None, 'metal', 0, [('startTag', (u'metal:main-slot', [(u'define-slot', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1))])), ('endScope', ())])), ('setPosition', (9, 1)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('rawtextColumn', (u'\n', 0))])), ('endScope', ())]}, 'master') (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: ({u'main': [('version', '1.6'), ('mode', 'html'), ('setPosition', (7, 0)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('beginScope', {u'define-macro': u'main'}), ('optTag', (u'metal:main-macro', None, 'metal', 0, [('startTag', (u'metal:main-macro', [(u'define-macro', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1)), ('setPosition', (8, 1)), ('defineSlot', (u'main', [('beginScope', {u'define-slot': u'main'}), ('optTag', (u'metal:main-slot', None, 'metal', 0, [('startTag', (u'metal:main-slot', [(u'define-slot', u'main', 'metal')]))], [('rawtextColumn', (u'\n\t', 1))])), ('endScope', ())])), ('setPosition', (9, 1)), ('setSourceFile', 'file:/home/moo/workspace2/collective.skinny/collective/skinny/skins/skinny_faux_layer/main_template.pt'), ('rawtextColumn', (u'\n', 0))])), ('endScope', ())]}, 'master'))</pre>
</div>
<p>Some template tries to call macro inside another template and the macro is not defined in the target template.</p>
</div>
<div class="section" id="attributeerror-in-setroles-due-to-workflow-state-transition">
<h2><a class="toc-backref" href="#id6">AttributeError in setRoles due to workflow state transition</a><a class="headerlink" href="#attributeerror-in-setroles-due-to-workflow-state-transition" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>Traceback (innermost last):
Module ZPublisher.Publish, line 115, in publish
Module ZPublisher.mapply, line 88, in mapply
Module ZPublisher.Publish, line 41, in call_object
Module Products.CMFPlone.FactoryTool, line 361, in __call__
Module Products.CMFPlone.FactoryTool, line 147, in __getitem__
Module Products.CMFPlone.PloneFolder, line 406, in invokeFactory
Module Products.CMFCore.TypesTool, line 934, in constructContent
Module Products.CMFCore.TypesTool, line 345, in constructInstance
Module Products.CMFCore.TypesTool, line 357, in _finishConstruction
Module Products.CMFCore.CMFCatalogAware, line 145, in notifyWorkflowCreated
Module Products.CMFCore.WorkflowTool, line 355, in notifyCreated
Module Products.DCWorkflow.DCWorkflow, line 392, in notifyCreated
Module Products.DCWorkflow.DCWorkflow, line 476, in _changeStateOf
Module Products.DCWorkflow.DCWorkflow, line 571, in _executeTransition
Module Products.DCWorkflow.DCWorkflow, line 435, in updateRoleMappingsFor
Module Products.DCWorkflow.utils, line 60, in modifyRolesForPermission
Module AccessControl.Permission, line 93, in setRoles
AttributeError: appname</pre>
</div>
<p>Possible reasons</p>
<ol class="arabic simple">
<li>You are using AnnotationStorage but you forgot to declare atapi.ATFieldProperty in your class body</li>
<li>You are inhering schema in Archetypes, but you do not inherit the class itself</li>
</ol>
</div>
<div class="section" id="add-on-installer-error-too-many-values-to-unpack">
<h2><a class="toc-backref" href="#id7">Add-on installer error: too many values to unpack</a><a class="headerlink" href="#add-on-installer-error-too-many-values-to-unpack" title="Permalink to this headline">Â¶</a></h2>
<p>An exception prevents running a quick installer.</p>
<p>Example:</p>
<div class="highlight-python"><pre>  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 589, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 475, in installProduct
   - __traceback_info__: ('gomobile.mobile',)
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 396, in snapshotPortal
  Module five.localsitemanager.registry, line 194, in registeredUtilities
  Module zope.component.registry, line 127, in registeredUtilities
ValueError: too many values to unpack</pre>
</div>
<p>Reason:</p>
<p>You have run Data.fs with zope.component 3.5.1, but later downgraded / moved Data.fs.
Pin zope.component to 3.5.1.</p>
<p><a class="reference external" href="http://plone.org/support/forums/general#nabble-td3257712%7Ca3257712">See discussion</a>.</p>
</div>
<div class="section" id="add-on-installer-error-this-object-was-originally-created-by-a-product-that-is-no-longer-installed">
<h2><a class="toc-backref" href="#id8">Add-on installer error: This object was originally created by a product that is no longer installed</a><a class="headerlink" href="#add-on-installer-error-this-object-was-originally-created-by-a-product-that-is-no-longer-installed" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>2009-10-18 13:11:20 ERROR Zope.SiteErrorLog 1255860680.760.514176531634 http://localhost:8080/twinapex/portal_quickinstaller/installProducts
Traceback (innermost last):
  Module ZPublisher.Publish, line 125, in publish
  Module Zope2.App.startup, line 238, in commit
  Module transaction._manager, line 93, in commit
  Module transaction._transaction, line 325, in commit
  Module transaction._transaction, line 424, in _commitResources
  Module ZODB.Connection, line 541, in commit
  Module ZODB.Connection, line 586, in _commit
  Module ZODB.Connection, line 620, in _store_objects
  Module ZODB.serialize, line 407, in serialize
  Module OFS.Uninstalled, line 40, in __getstate__
SystemError: This object was originally created by a product that
            is no longer installed.  It cannot be updated.
            (&lt;Salt at broken&gt;)</pre>
</div>
<p>Data.fs contains objects for which the code is not present.
You have probably moved Data.fs or edited buildout.cfg.</p>
<p>Check that eggs and zcml contain all necessary products in buildout.cfg.</p>
<p>Discussion</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.org/support/forums/general#nabble-td3523234">http://plone.org/support/forums/general#nabble-td3523234</a></li>
<li><a class="reference external" href="http://article.gmane.org/gmane.comp.web.zope.plone.setup/3232">http://article.gmane.org/gmane.comp.web.zope.plone.setup/3232</a></li>
</ul>
</div>
<div class="section" id="z3c-form-based-form-updatewidgets-raises-componentlookuperror">
<h2><a class="toc-backref" href="#id9">z3c.form based form updateWidgets() raises ComponentLookupError</a><a class="headerlink" href="#z3c-form-based-form-updatewidgets-raises-componentlookuperror" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>Error in test test_render_form (gomobile.convergence.tests.test_mobile_overrides.TestMobileOverrides)
Traceback (most recent call last):
  File "/Users/moo/twinapex/twinapex/parts/zope2/lib/python/Testing/ZopeTestCase/profiler.py", line 98, in __call__
    testMethod()
  File "/Users/moo/twinapex/twinapex/src/gomobile.convergence/gomobile/convergence/tests/test_mobile_overrides.py", line 65, in test_render_form
    result()
  File "/Users/moo/twinapex/twinapex/eggs/z3c.form-1.9.0-py2.4.egg/z3c/form/form.py", line 189, in __call__
    self.update()
  File "/Users/moo/twinapex/twinapex/eggs/z3c.form-1.9.0-py2.4.egg/z3c/form/form.py", line 184, in update
    super(Form, self).update()
  File "/Users/moo/twinapex/twinapex/eggs/z3c.form-1.9.0-py2.4.egg/z3c/form/form.py", line 134, in update
    self.updateWidgets()
  File "/Users/moo/twinapex/twinapex/eggs/z3c.form-1.9.0-py2.4.egg/z3c/form/form.py", line 120, in updateWidgets
    self.widgets = zope.component.getMultiAdapter(
  File "/Users/moo/twinapex/twinapex/eggs/zope.component-3.5.1-py2.4.egg/zope/component/_api.py", line 104, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
ComponentLookupError: ((&lt;Products.Five.metaclass.documentoverriderform object at 0x711c6f0&gt;, &lt;HTTPRequest, URL=http://nohost&gt;, &lt;ATDocument at /plone/doc&gt;), &lt;InterfaceClass z3c.form.interfaces.IWidgets&gt;, u'')</pre>
</div>
<p>Reason: To use z3c.form based forms z3c.form.interfaces.IFormRequest must be enabled for HTTP request
object to make form layer adaptions work.</p>
<p>How to fix:</p>
<ul class="simple">
<li>Wrap your forms with plone.z3cform.layout.wrap_form() call as instructed in plone.z3cform README</li>
</ul>
<p>The same error occurs if plone.app.z3cform, plone.z3cform and z3c.form are not properly included through ZCML.
In order to be sure that those modules are properly included, you can add the following lines into your configure.zcml</p>
<div class="highlight-xml"><div class="highlight"><pre><span class="nt">&lt;include</span> <span class="na">package=</span><span class="s">&quot;plone.app.z3cform&quot;</span> <span class="nt">/&gt;</span>
<span class="nt">&lt;include</span> <span class="na">package=</span><span class="s">&quot;plone.z3cform&quot;</span> <span class="nt">/&gt;</span>
<span class="nt">&lt;include</span> <span class="na">package=</span><span class="s">&quot;z3c.form&quot;</span> <span class="nt">/&gt;</span>
</pre></div>
</div>
<p>...or you can use autoinclude feature for Plone 3.3+</p>
<p>in configure.zcml</p>
<div class="highlight-xml"><div class="highlight"><pre><span class="nt">&lt;includeDependencies</span> <span class="na">package=</span><span class="s">&quot;.&quot;</span> <span class="nt">/&gt;</span>
</pre></div>
</div>
<p>and then your add-on product setup.py file:</p>
<div class="highlight-python"><pre>  install_requires=[
    'setuptools',
    'plone.app.z3cform',
    # -*- Extra requirements: -*-
],</pre>
</div>
<p>Also remember to run Plone add-on installer for plone.app.z3cform (though it is unrelated to this error).</p>
</div>
<div class="section" id="notfound-error-page-not-found-when-accessing-manage-portlets">
<h2><a class="toc-backref" href="#id10">NotFound error (Page not found) when accessing &#64;&#64;manage-portlets</a><a class="headerlink" href="#notfound-error-page-not-found-when-accessing-manage-portlets" title="Permalink to this headline">Â¶</a></h2>
<p>If you get <em>Page not found</em> error when accessing &#64;&#64;manage-portlets the first thing
you need to do is to enable logging of NotFound exceptions in ZMI in error_log.</p>
<p>After that reload &#64;&#64;manage-portlets.</p>
<p>When you try to access &#64;&#64;manage-portlets an exception a NotFound exception is raised:</p>
<div class="highlight-python"><pre>2009-11-09 12:56:13 ERROR Zope.SiteErrorLog 1257764173.180.738005333766 http://localhost:8080/yourinstance/@@manage-portlets
Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
    Module Products.PageTemplates.Expressions, line 223, in evaluateStructure
    ...
  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/Users/moo/workspace/plonetheme.yourinstance/plonetheme/yourinstance/skins/plonetheme_yourinstance_custom_templates/main_template.pt
   - Line 92, Column 18
   - Expression: &lt;StringExpr u'plone.leftcolumn'&gt;
   - Names:
      {'container': &lt;PloneSite at /yourinstance&gt;,
       'context': &lt;PloneSite at /yourinstance&gt;,
       'default': &lt;object object at 0x194520&gt;,
       'here': &lt;PloneSite at /yourinstance&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': (&lt;Products.Five.metaclass.SimpleViewClass from /Users/moo/yourinstance/eggs/plone.app.portlets-1.2-py2.4.egg/plone/app/portlets/browser/templates/manage-contextual.pt object at 0x67e43b0&gt;,)},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0x73b59b8&gt;,
       'request': &lt;HTTPRequest, URL=http://localhost:8080/yourinstance/@@manage-portlets&gt;,
       'root': &lt;Application at &gt;,
       'template': &lt;ImplicitAcquirerWrapper object at 0x73b29f0&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;,
       'view': &lt;Products.Five.metaclass.SimpleViewClass from /Users/moo/yourinstance/eggs/plone.app.portlets-1.2-py2.4.egg/plone/app/portlets/browser/templates/manage-contextual.pt object at 0x67e43b0&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0x73b23d0&gt;}
  Module Products.Five.browser.providerexpression, line 37, in __call__
  ...
  Module zope.tales.tales, line 696, in evaluate
   - URL: index
   - Line 18, Column 12
   - Expression: &lt;PathExpr standard:'view/addable_portlets'&gt;
   - Names:
      {'container': &lt;PloneSite at /yourinstance&gt;,
       'context': &lt;PloneSite at /yourinstance&gt;,
       'default': &lt;object object at 0x194520&gt;,
       'here': &lt;PloneSite at /yourinstance&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0x7941be8&gt;,
       'request': &lt;HTTPRequest, URL=http://localhost:8080/yourinstance/@@manage-portlets&gt;,
       'root': &lt;Application at &gt;,
       'template': &lt;ImplicitAcquirerWrapper object at 0x78be050&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;,
       'view': &lt;plone.app.portlets.browser.editmanager.ContextualEditPortletManagerRenderer object at 0x789eb90&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0x790a870&gt;}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 163, in _eval
  Module Products.PageTemplates.Expressions, line 125, in render
  Module plone.app.portlets.browser.editmanager, line 154, in addable_portlets
  Module plone.app.portlets.browser.editmanager, line 149, in check_permission
  Module OFS.Traversable, line 301, in restrictedTraverse
  Module OFS.Traversable, line 284, in unrestrictedTraverse
   - __traceback_info__: ([], 'collective.easytemplate.TemplatedPortlet')
NotFound: collective.easytemplate.TemplatedPortlet</pre>
</div>
<p>This usually means that your site has an portlet assignment which code is not present anymore.</p>
<p>In this case you can see that portlet type &quot;collective.easytemplate.TemplatedPortlet&quot; is missing.</p>
<p>Ã Check that you include the corresponding product (collective.easytemplate) in eggs= section in buildout.cfg</p>
<ul class="simple">
<li>Reinstall removed egg which has the code for the portlet</li>
<li>Check that you include the corresponding product (collective.easytemplate) in zcml= section in buildout.cfg</li>
<li>Make sure that portlet name is the same in ZCML and GenericSetup XML</li>
<li>Make sure you use &lt;include package=&quot;.portlets&quot; /&gt; in your code</li>
</ul>
<div class="section" id="manually-removing-the-portlet">
<h3><a class="toc-backref" href="#id11">Manually removing the portlet</a><a class="headerlink" href="#manually-removing-the-portlet" title="Permalink to this headline">Â¶</a></h3>
<p>If you have a traceback like this:</p>
<div class="highlight-python"><pre>URL: index
Line 18, Column 12
Expression: &lt;PathExpr standard:'view/addable_portlets'&gt;
Names:
{'container': &lt;ATFolder at /webandmobile/support&gt;,
 'context': &lt;ATFolder at /webandmobile/support&gt;,
 'default': &lt;object object at 0x7f7e3af1a200&gt;,
 'here': &lt;ATFolder at /webandmobile/support&gt;,
 'loop': {},
 'nothing': None,
 'options': {'args': ()},
 'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0x11dee1b8&gt;,
 'request': &lt;HTTPRequest, URL=http://webandmobile.mfabrik.com/support/@@manage-portlets&gt;,
 'root': &lt;Application at &gt;,
 'template': &lt;ImplicitAcquirerWrapper object at 0x7f7e2a9199d0&gt;,
 'traverse_subpath': [],
 'user': &lt;PropertiedUser 'admin'&gt;,
 'view': &lt;plone.app.portlets.browser.editmanager.ContextualEditPortletManagerRenderer object at 0xf0526d0&gt;,
 'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0x7f7e2a919810&gt;}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 163, in _eval
Module Products.PageTemplates.Expressions, line 125, in render
Module plone.app.portlets.browser.editmanager, line 154, in addable_portlets
Module plone.app.portlets.browser.editmanager, line 149, in check_permission
Module OFS.Traversable, line 301, in restrictedTraverse
Module OFS.Traversable, line 284, in unrestrictedTraverse
__traceback_info__: ([], 'gomobile.convergence.ContentMedia')
NotFound: gomobile.convergence.ContentMedia</pre>
</div>
<p>It usually means that there is a portlet in your content which product code has been removed.</p>
<p>Reinstall the add-on providing the portlet, remove the portlet and then uninstall the add-on again.</p>
</div>
</div>
<div class="section" id="attributeerror-getphysicalpath">
<h2><a class="toc-backref" href="#id12">AttributeError: getPhysicalPath()</a><a class="headerlink" href="#attributeerror-getphysicalpath" title="Permalink to this headline">Â¶</a></h2>
<div class="highlight-python"><pre>  Module zope.tal.talinterpreter, line 408, in do_startTag
  Module zope.tal.talinterpreter, line 485, in attrAction_tal
  Module Products.PageTemplates.Expressions, line 230, in evaluateText
  Module zope.tales.tales, line 696, in evaluate
   - URL: edit_header
   - Line 25, Column 14
   - Expression: &lt;PythonExpr (view.getHeaderDefiner().absolute_url())&gt;
   - Names:
      {'container': &lt;Frontpage at /yourinstance/matkailijalle/yourinstance-1&gt;,
       'context': &lt;Frontpage at /yourinstance/matkailijalle/yourinstance-1&gt;,
       'default': &lt;object object at 0x7fabf9cec1f0&gt;,
       'here': &lt;Frontpage at /yourinstance/matkailijalle/yourinstance-1&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0xe617d88&gt;,
       'request': &lt;HTTPRequest, URL=http://localhost:9444/yourinstance/matkailijalle/yourinstance-1/@@edit_header&gt;,
       'root': &lt;Application at &gt;,
       'template': &lt;ImplicitAcquirerWrapper object at 0xe6105d0&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;,
       'view': &lt;Products.Five.metaclass.EditHeaderBehaviorView object at 0xe51ed10&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0xe610c10&gt;}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.getHeaderDefiner().absolute_url())
  Module &lt;string&gt;, line 0, in ?
  Module OFS.Traversable, line 64, in absolute_url
  Module OFS.Traversable, line 117, in getPhysicalPath
AttributeError: getPhysicalPath</pre>
</div>
<p>Another possibility:</p>
<div class="highlight-python"><pre>AttributeError: absolute_url</pre>
</div>
<p>This usually means that you should have used context.aq_inner when you have used context.
absolute_url() tries to get the path to the object, but object parent is set to view (context.aq_parent)
instead of real container object (context.aq_inner.aq_parent).</p>
<div class="admonition warning">
<p class="first admonition-title">Warning</p>
<p class="last">When setting a member attribute in BrowserView, the acquisition parent of objec changes to BrowserView instance.
All member attributes receive ImplicitAcquisitionWrapper automatically.</p>
</div>
<div class="section" id="demostration">
<h3><a class="toc-backref" href="#id13">Demostration</a><a class="headerlink" href="#demostration" title="Permalink to this headline">Â¶</a></h3>
<p>We try to set BrowserView member attribute defining_context to be some context object.</p>
<blockquote>
(Pdb) self.defining_context = context
(Pdb) context.aq_parent
&lt;PloneSite at /plone&gt;
(Pdb) self.defining_context.aq_parent
&lt;Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750&gt;
(Pdb) self.defining_context.aq_inner.aq_parent
&lt;Products.Five.metaclass.HeaderAnimationHelper object at 0xadb5750&gt;
(Pdb) self.defining_context.aq_parent.aq_parent
&lt;ATDocument at /plone/doc&gt;
(Pdb) self.defining_context.aq_parent.aq_parent.aq_inner
&lt;ATDocument at /plone/doc&gt;
(Pdb) self.defining_context.aq_parent.aq_parent.aq_parent
&lt;PloneSite at /plone&gt;</blockquote>
<p>To get the real object (as it was before set was called) you can create a helper getter:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">getDefiningContext</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Un-fuse automatically injected view from the acquisition chain</span>

<span class="sd">    @return: Real defining context object without bad acquistion</span>
<span class="sd">    &quot;&quot;&quot;</span>
    <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">defining_context</span> <span class="ow">is</span> <span class="ow">not</span> <span class="bp">None</span><span class="p">:</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">defining_context</span><span class="o">.</span><span class="n">aq_parent</span><span class="o">.</span><span class="n">aq_inner</span><span class="o">.</span><span class="n">aq_parent</span>
    <span class="k">return</span> <span class="bp">None</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="runtimeerror-maximum-recursion-depth-exceeded-archetypes-field-problem">
<h2><a class="toc-backref" href="#id14">RuntimeError: maximum recursion depth exceeded (Archetypes field problem)</a><a class="headerlink" href="#runtimeerror-maximum-recursion-depth-exceeded-archetypes-field-problem" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>   atapi.ImageField(
        'memberimage',
        # storage=atapi.AnnotationStorage(), # paster version
        storage=atapi.AttributeStorage(), # results in "max recursion depth exceeded" error
        widget=atapi.ImageWidget(
            label=_(u"New Field"),
            description=_(u"Field description"),
        ),
        validators=('isNonEmptyFile'),
        original_size=(600,600),
        sizes={ 'mini' : (80,80),
                'normal' : (200,200),
                'big' : (300,300),
                'maxi' : (500,500)},
    ),


This results in an exception when I try to access the object:

   - __traceback_info__: ('memberimage', &lt;TTMemberImage at tt_member_image.2010-01-23.8138248069&gt;, {'field': &lt;Field memberimage(image:rw)&gt;})
  Module Products.Archetypes.Storage, line 96, in get
  Module Products.Archetypes.utils, line 808, in shasattr
  Module Products.Archetypes.fieldproperty, line 101, in __get__
  Module Products.Archetypes.Field, line 997, in get
  Module Products.Archetypes.Field, line 709, in get
   - __traceback_info__: ('memberimage', &lt;TTMemberImage at tt_member_image.2010-01-23.8138248069&gt;, {'field': &lt;Field memberimage(image:rw)&gt;})
RuntimeError: maximum recursion depth exceeded</pre>
</div>
<p>Reason: Schema fields using AttributeStorage (usually images, files) <strong>cannot</strong> have ATFieldProperty in the class:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">Sample</span><span class="p">(</span><span class="n">base</span><span class="o">.</span><span class="n">ATCTContent</span><span class="p">):</span>

    <span class="c"># This does not work with AttributeStorage</span>
    <span class="n">memberimage</span> <span class="o">=</span> <span class="n">atapi</span><span class="o">.</span><span class="n">ATFieldProperty</span><span class="p">(</span><span class="s">&#39;memberimage&#39;</span><span class="p">)</span>
</pre></div>
</div>
<p>To fix this simply remobe ATFieldProperty() declaration for the problematic field. You cannot
access the field value anymore by calling <em>object.memberimage</em> but you need to call <em>object.getMemberimage()</em> instead.</p>
</div>
<div class="section" id="invalid-or-duplicate-property-id">
<h2><a class="toc-backref" href="#id15">Invalid or Duplicate property id</a><a class="headerlink" href="#invalid-or-duplicate-property-id" title="Permalink to this headline">Â¶</a></h2>
<p>The following exception may appear during Plone migration to the newer version:</p>
<div class="highlight-python"><pre>    *   Dry run selected.
    * Starting the migration from version: 3.1.4
    * Attempting to upgrade from: 3.1.4
    * Upgrade aborted
    * Error type: zExceptions.BadRequest
    * Error value: Invalid or duplicate property id
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/MigrationTool.py",
line 210, in upgrade newv, msgs = self._upgrade(newv)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/MigrationTool.py",
line 321, in _upgrade res = function(self.aq_parent)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/migrations/v3_1/final_three1x.py",
line 15, in three14_three15 loadMigrationProfile(portal,
'profile-Products.CMFPlone.migrations:3.1.3-3.1.4')
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/migrations/migration_util.py",
line 107, in loadMigrationProfile tool.runAllImportStepsFromProfile(profile,
purge_old=False)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/tool.py",
line 390, in runAllImportStepsFromProfile
ignore_dependencies=ignore_dependencies)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/tool.py",
line 1179, in _runImportStepsFromContext message =
self._doRunImportStep(step, context)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/tool.py",
line 1090, in _doRunImportStep return handler(context)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/exportimport/propertiestool.py",
line 37, in importPloneProperties importer.body = body
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/utils.py",
line 544, in _importBody self._importNode(dom.documentElement)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/exportimport/propertiestool.py",
line 103, in _importNode self._initObjects(node)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/exportimport/propertiestool.py",
line 154, in _initObjects importer.node = child
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Plone-3.3-py2.4.egg/Products/CMFPlone/exportimport/propertiestool.py",
line 77, in _importNode self._initProperties(node)
    * File
"/usr/local/Plone3.2.3/buildout-cache/eggs/Products.GenericSetup-1.4.5-py2.4.egg/Products/GenericSetup/utils.py",
line 724, in _initProperties obj._setProperty(prop_id, val, prop_type)
    * File
"/usr/local/Plone3.2.3/Zope-2.10.7-final-py2.4/lib/python/OFS/PropertyManager.py",
line 186, in _setProperty raise BadRequest, 'Invalid or duplicate property
id'
    * End of upgrade path, migration has finished
    * The upgrade path did NOT reach current version
    * Migration has failed
    * Dry run selected, transaction aborted</pre>
</div>
<p>It is caused by a property (site setting) which already exists and migration tries to create it.
The usual reason is that one has edited site settings in new Plone version before running the migration.</p>
<p>Try remove violating property ids from the site_properties manually in Zope.</p>
<p>Potential candidates to be removed:</p>
<ul class="simple">
<li>enable_inline_editing</li>
<li>lock_on_ttw_edit (boolean)</li>
</ul>
<p>Potential candidates which need to be added manually:</p>
<ul class="simple">
<li>redirect_links (boolean)</li>
</ul>
<p>More info:</p>
<ul class="simple">
<li><a class="reference external" href="http://www.mail-archive.com/setup&#64;lists.plone.org/msg03988.html">http://www.mail-archive.com/setup&#64;lists.plone.org/msg03988.html</a></li>
</ul>
</div>
<div class="section" id="traversalerror-no-traversable-adapter-found">
<h2><a class="toc-backref" href="#id16">TraversalError: No traversable adapter found</a><a class="headerlink" href="#traversalerror-no-traversable-adapter-found" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback (innermost last):</p>
<blockquote>
<ul class="simple">
<li>Module ZPublisher.Publish, line 202, in publish_module_standard</li>
<li>Module Products.LinguaPlone.patches, line 66, in new_publish</li>
<li>Module ZPublisher.Publish, line 150, in publish</li>
<li>Module Zope2.App.startup, line 221, in zpublisher_exception_hook</li>
<li>Module ZPublisher.Publish, line 119, in publish</li>
<li>Module ZPublisher.mapply, line 88, in mapply</li>
<li>Module ZPublisher.Publish, line 42, in call_object</li>
<li>Module Shared.DC.Scripts.Bindings, line 313, in __call__</li>
<li>Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec</li>
<li>Module Products.CMFCore.FSPageTemplate, line 216, in _exec</li>
<li>Module Products.CMFCore.FSPageTemplate, line 155, in pt_render</li>
<li>Module Products.PageTemplates.PageTemplate, line 98, in pt_render</li>
<li>Module zope.pagetemplate.pagetemplate, line 117, in pt_render
Warning: Macro expansion failed
Warning: zope.traversing.interfaces.TraversalError: ('No traversable adapter found',</li>
</ul>
</blockquote>
<p>This traceback is followed by long dump of template code internals.</p>
<p>Usual cause: Some add-on product fails to initialize.</p>
<p>Start Zope in foreground mode (bin/instance fg) to see which product fails.</p>
</div>
<div class="section" id="importerror-inappropriate-file-type-for-dynamic-loading">
<h2><a class="toc-backref" href="#id17">ImportError: Inappropriate file type for dynamic loading</a><a class="headerlink" href="#importerror-inappropriate-file-type-for-dynamic-loading" title="Permalink to this headline">Â¶</a></h2>
<p>Exception when starting Zope:</p>
<div class="highlight-python"><pre>  File "/Users/moo/twinapex/twinapex/parts/zope2/lib/python/ZConfig/datatypes.py", line 398, in get
    t = self.search(name)
  File "/Users/moo/twinapex/twinapex/parts/zope2/lib/python/ZConfig/datatypes.py", line 423, in search
    package = __import__(n, g, g, component)
  File "/Users/moo/twinapex/twinapex/parts/zope2/lib/python/Zope2/Startup/datatypes.py", line 20, in ?
    from ZODB.config import ZODBDatabase
  File "/Users/moo/twinapex/twinapex/eggs/ZODB3-3.8.2-py2.4-macosx-10.6-i386.egg/ZODB/__init__.py", line 20, in ?
    from persistent import TimeStamp
  File "/Users/moo/twinapex/twinapex/eggs/ZODB3-3.8.2-py2.4-macosx-10.6-i386.egg/persistent/__init__.py", line 19, in ?
    from cPersistence import Persistent, GHOST, UPTODATE, CHANGED, STICKY
ImportError: Inappropriate file type for dynamic loading</pre>
</div>
<p>You probably have files lying over from wrong CPU architecture</p>
<ul class="simple">
<li>Hand copied eggs between servers</li>
<li>Migrated OS to new version</li>
<li>You have several Python interpreters installed and you try to run Zope using
the wrong interpreter (the one which the code is not compiled for)</li>
</ul>
<p>How to solve problem</p>
<ul class="simple">
<li>Delete /parts and /eggs buildout folders, run bootstrap, run buildout.</li>
</ul>
</div>
<div class="section" id="badrequest-the-id-xxx-is-invalid-it-is-already-in-use">
<h2><a class="toc-backref" href="#id18">BadRequest: The id &quot;xxx&quot; is invalid - it is already in use.</a><a class="headerlink" href="#badrequest-the-id-xxx-is-invalid-it-is-already-in-use" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback example:</p>
<div class="highlight-python"><pre>...
Module Products.CMFFormController.Script, line 145, in __call__
Module Products.CMFCore.FSPythonScript, line 140, in __call__
Module Shared.DC.Scripts.Bindings, line 313, in __call__
Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
Module Products.CMFCore.FSPythonScript, line 196, in _exec
Module None, line 1, in content_edit
&lt;FSControllerPythonScript at /xxx/content_edit used for /xxx/sisalto/lomapalvelut/portal_factory/HolidayService/aktiviteetit&gt;
Line 1
Module Products.CMFCore.FSPythonScript, line 140, in __call__
Module Shared.DC.Scripts.Bindings, line 313, in __call__
Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
Module Products.CMFCore.FSPythonScript, line 196, in _exec
Module None, line 9, in content_edit_impl
&lt;FSPythonScript at /xxx/content_edit_impl used for /xxx/sisalto/lomapalvelut/portal_factory/HolidayService/aktiviteetit&gt;
Line 9
Module Products.CMFPlone.FactoryTool, line 264, in doCreate
Module Products.ATContentTypes.lib.constraintypes, line 281, in invokeFactory
Module Products.CMFCore.PortalFolder, line 315, in invokeFactory
Module Products.CMFCore.TypesTool, line 716, in constructContent
Module Products.CMFCore.TypesTool, line 276, in constructInstance
Module Products.CMFCore.TypesTool, line 450, in _constructInstance
Module xxx.app.content.holidayservice, line 7, in addHolidayService
Module OFS.ObjectManager, line 315, in _setObject
Module Products.CMFCore.PortalFolder, line 333, in _checkId
Module OFS.ObjectManager, line 102, in checkValidId
BadRequest: The id "holidayservice.2010-03-18.4474765045" is invalid - it is already in use.</pre>
</div>
<p>TODO: Not really sure why this happens.</p>
<p>Try portal_catalog rebuild as a fix.</p>
</div>
<div class="section" id="exception-type-name-not-specified-in-createobject">
<h2><a class="toc-backref" href="#id19">Exception: Type name not specified in createObject</a><a class="headerlink" href="#exception-type-name-not-specified-in-createobject" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>Module ZPublisher.Publish, line 119, in publish
Module ZPublisher.mapply, line 88, in mapply
Module ZPublisher.Publish, line 42, in call_object
Module Products.CMFFormController.FSControllerPythonScript, line 104, in __call__
Module Products.CMFFormController.Script, line 145, in __call__
Module Products.CMFCore.FSPythonScript, line 140, in __call__
Module Shared.DC.Scripts.Bindings, line 313, in __call__
Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
Module Products.CMFCore.FSPythonScript, line 196, in _exec
Module None, line 11, in createObject
&lt;FSControllerPythonScript at /xxx/createObject used for /xxx/sisalto/lomapalvelut&gt;
Line 11
Exception: Type name not specified</pre>
</div>
<p>This is TODO</p>
</div>
<div class="section" id="unauthorized-the-object-is-marked-as-private">
<h2><a class="toc-backref" href="#id20">Unauthorized: The object is marked as private</a><a class="headerlink" href="#unauthorized-the-object-is-marked-as-private" title="Permalink to this headline">Â¶</a></h2>
<p>This error is raised when you try to access view functions or objects
for a view, which you call manually from the code.</p>
<p>Example traceback:</p>
<div class="highlight-python"><pre>  File "/home/moo/twinapex/parts/zope2/lib/python/zope/tales/expressions.py", line 124, in _eval
    ob = self._traverser(ob, element, econtext)
  File "/home/moo/twinapex/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 105, in trustedBoboAwareZopeTraverse
    request=request)
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/traversing/adapters.py", line 164, in traversePathElement
    return traversable.traverse(nm, further_path)
  File "/home/moo/twinapex/parts/zope2/lib/python/zope/traversing/adapters.py", line 44, in traverse
    attr = getattr(subject, name, _marker)
  File "/home/moo/twinapex/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 184, in __getattr__
    return guarded_getattr(self._wrapped, name, default)
  File "/home/moo/twinapex/parts/zope2/lib/python/AccessControl/ImplPython.py", line 563, in validate
    self._context)
  File "/home/moo/twinapex/parts/zope2/lib/python/AccessControl/ImplPython.py", line 443, in validate
    accessed, container, name, value, context)
  File "/home/moo/twinapex/parts/zope2/lib/python/AccessControl/ImplPython.py", line 808, in raiseVerbose
    raise Unauthorized(text)
Unauthorized: The object is marked as private.  Access to 'showVideo' of (Products.Five.metaclass.SimpleViewClass from /home/moo/twinapex/src/mfabrik.app/mfabrik/app/browser/campaigntopview.pt object at 0x11003a0c) denied.</pre>
</div>
<p>View acquisition chain is not properly set up and the security manager cannot traverse acquisition
chain parents to properly determine permissions.</p>
<p>You need to use __of__() method to set-up the acquisition chain for the view:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">getHeadingView</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Check if we have campaign view avaiable for this content and use it.</span>
<span class="sd">    &quot;&quot;&quot;</span>
    <span class="n">view</span> <span class="o">=</span> <span class="n">queryMultiAdapter</span><span class="p">((</span><span class="bp">self</span><span class="o">.</span><span class="n">context</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">request</span><span class="p">),</span> <span class="n">name</span><span class="o">=</span><span class="s">&quot;mfabrik_heading&quot;</span><span class="p">)</span>
    <span class="n">view</span> <span class="o">=</span> <span class="n">view</span><span class="o">.</span><span class="n">__of__</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">context</span><span class="p">)</span> <span class="c"># &lt;---------- here</span>
    <span class="k">return</span> <span class="n">view</span>
</pre></div>
</div>
</div>
<div class="section" id="importerror-no-module-named-pil">
<h2><a class="toc-backref" href="#id21">ImportError: No module named PIL</a><a class="headerlink" href="#importerror-no-module-named-pil" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>Traceback (most recent call last):
  File "/home/moo/isleofback/parts/zope2/lib/python/OFS/Application.py", line 709, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/__init__.py", line 64, in ?
    import Products.ATContentTypes.content
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/__init__.py", line 26, in ?
    import Products.ATContentTypes.content.link
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/link.py", line 39, in ?
    from Products.ATContentTypes.content.base import registerATCT
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/base.py", line 63, in ?
    from Products.CMFPlone.PloneFolder import ReplaceableWrapper
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/__init__.py", line 215, in ?
    from browser import ploneview
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/browser/ploneview.py", line 12, in ?
    from Products.CMFPlone import utils
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/utils.py", line 6, in ?
    from PIL import Image
ImportError: No module named PIL
Traceback (most recent call last):
  File "/home/moo/isleofback/bin/idelauncher.py", line 140, in ?
    execfile(ZOPE_RUN)
  File "/home/moo/isleofback/bin/../parts/zope2/lib/python/Zope2/Startup/run.py", line 56, in ?
    run()
  File "/home/moo/isleofback/bin/../parts/zope2/lib/python/Zope2/Startup/run.py", line 21, in run
    starter.prepare()
  File "/home/moo/isleofback/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 102, in prepare
    self.startZope()
  File "/home/moo/isleofback/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 278, in startZope
    Zope2.startup()
  File "/home/moo/isleofback/parts/zope2/lib/python/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/moo/isleofback/parts/zope2/lib/python/Zope2/App/startup.py", line 45, in startup
    OFS.Application.import_products()
  File "/home/moo/isleofback/parts/zope2/lib/python/OFS/Application.py", line 686, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/home/moo/isleofback/parts/zope2/lib/python/OFS/Application.py", line 709, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/__init__.py", line 64, in ?
    import Products.ATContentTypes.content
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/__init__.py", line 26, in ?
    import Products.ATContentTypes.content.link
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/link.py", line 39, in ?
    from Products.ATContentTypes.content.base import registerATCT
  File "/home/moo/isleofback/eggs/Products.ATContentTypes-1.3.4-py2.4.egg/Products/ATContentTypes/content/base.py", line 63, in ?
    from Products.CMFPlone.PloneFolder import ReplaceableWrapper
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/__init__.py", line 215, in ?
    from browser import ploneview
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/browser/ploneview.py", line 12, in ?
    from Products.CMFPlone import utils
  File "/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/utils.py", line 6, in ?
    from PIL import Image
ImportError: No module named PIL</pre>
</div>
<p>Python Imaging Library is not properly installed. The default PIL package does not work nicely as egg.</p>
<p>Remove all existing PIL eggs from buildout/eggs folder.</p>
<p>Install PIL for your development Python environment:</p>
<div class="highlight-python"><pre>easy_install http://dist.repoze.org/PIL-1.1.6.tar.gz</pre>
</div>
</div>
<div class="section" id="notfound-while-accessing-a-browserview-based-view">
<h2><a class="toc-backref" href="#id22">NotFound while accessing a BrowserView based view</a><a class="headerlink" href="#notfound-while-accessing-a-browserview-based-view" title="Permalink to this headline">Â¶</a></h2>
<p>You'll get a NotFound error when accessing view using view traverse notation,
event though the view exist.</p>
<p>Example URL:</p>
<div class="highlight-python"><pre>http://yoursite/@@myview</pre>
</div>
<p>Example traceback:</p>
<div class="highlight-python"><pre>Traceback (innermost last):
  Module ZPublisher.Publish, line 110, in publish
  Module ZPublisher.BaseRequest, line 506, in traverse
  Module ZPublisher.HTTPResponse, line 686, in debugError
NotFound:   &lt;h2&gt;Site Error&lt;/h2&gt;</pre>
</div>
<p>This is because there is an exception raised in your view's __init__()
method. Views are Zope multi-adapters. Exception in multi-adapter factory
method causes ComponentLookUpError. Zope 2 publisher translates
this to NotFound error.</p>
<p>How to fix</p>
<ul class="simple">
<li>Put <a class="reference internal" href="../testing_and_debugging/pdb.html"><em>pdb break statement</em></a> to the beginning of the __init__()
method of your view. Then step through view code to see where the exception is raisen.</li>
<li>If your view does not have __init__() method, then copy the source code __init__() method
to your view class from the first parent class which has a view</li>
</ul>
</div>
<div class="section" id="contentproviderlookuperror-plone-htmlhead">
<h2><a class="toc-backref" href="#id23">ContentProviderLookupError: plone.htmlhead</a><a class="headerlink" href="#contentproviderlookuperror-plone-htmlhead" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/home/moo/isleofback/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/skins/plone_templates/main_template.pt
   - Line 39, Column 4
   - Expression: &lt;StringExpr u'plone.htmlhead'&gt;
   - Names:
      {'container': &lt;PloneSite at /isleofback&gt;,
       'context': &lt;PloneSite at /isleofback&gt;,
       'default': &lt;object object at 0xb75f2528&gt;,
       'here': &lt;PloneSite at /isleofback&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': (&lt;isleofback.app.browser.company.CompanyCreationForm object at 0xea5e80c&gt;,)},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0xea62dcc&gt;,
       'request': &lt;HTTPRequest, URL=http://localhost:9666/isleofback/@@create_company&gt;,
       'root': &lt;Application at &gt;,
       'template': &lt;ImplicitAcquirerWrapper object at 0xea62bcc&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;,
       'view': &lt;UnauthorizedBinding: context&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0xea62d2c&gt;}
  Module Products.Five.browser.providerexpression, line 25, in __call__
ContentProviderLookupError: plone.htmlhead</pre>
</div>
<p>This is not a bug in Zope. It is caused by trying to render a Plone page frame in an context
which has not acquisition chain properly set up. Plone <tt class="docutils literal"><span class="pre">main_template.pt</span></tt>
tries to look up viewlet managers by
acquistion traversing to parent objects. <tt class="docutils literal"><span class="pre">plone.htmlhead</span></tt> is the first viewlet manager to
be looked up like this, and it will fail firstly.</p>
<p>Some possible causes</p>
<ul class="simple">
<li>You are trying to embed main_template inside form/view which is already rendered in main_template frame.
Please see how to <a class="reference internal" href="../forms/z3c.form.html"><em>embed forms and wrap forms manually</em></a>.</li>
<li>You might be using wrong ViewPageTemplate import (Five vs. zope.pagetemplate - explained elsewhere in this documentation)</li>
<li>Make sure that you call __of__() method for views and other objects you construct by hand
which expects themselves to be in the acquisition chain (normally discovered by traversing)</li>
</ul>
<p>See</p>
<ul class="simple">
<li><a class="reference external" href="https://bugs.launchpad.net/zope2/+bug/176566">https://bugs.launchpad.net/zope2/+bug/176566</a></li>
</ul>
</div>
<div class="section" id="error-while-installing-a-new-portlet-portlets-xml-unbound-prefix">
<h2><a class="toc-backref" href="#id24">Error while installing a new portlet portlets.xml: unbound prefix</a><a class="headerlink" href="#error-while-installing-a-new-portlet-portlets-xml-unbound-prefix" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>Traceback (innermost last):
  Module plone.postpublicationhook.hook, line 74, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 589, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 526, in installProduct
   - __traceback_info__: ('mfabrik.app',)
  Module Products.GenericSetup.tool, line 390, in runAllImportStepsFromProfile
   - __traceback_info__: profile-mfabrik.app:default
  Module Products.GenericSetup.tool, line 1179, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1090, in _doRunImportStep
   - __traceback_info__: portlets
  Module plone.app.portlets.exportimport.portlets, line 707, in importPortlets
  Module Products.GenericSetup.utils, line 543, in _importBody
ExpatError: portlets.xml: unbound prefix: line 15, column 1</pre>
</div>
<p>Answer:</p>
<p>You have <tt class="docutils literal"><span class="pre">i18n:attributes=&quot;title;</span> <span class="pre">description&quot;</span></tt> in your portlets.xml. Remove it or declare i18n namespace in XML.</p>
</div>
<div class="section" id="importerror-couldn-t-import-zpublishereventsbackport">
<h2><a class="toc-backref" href="#id25">ImportError: Couldn't import ZPublisherEventsBackport</a><a class="headerlink" href="#importerror-couldn-t-import-zpublishereventsbackport" title="Permalink to this headline">Â¶</a></h2>
<p>The following traceback on instance start-up:</p>
<div class="highlight-python"><pre>  File "/Users/moo/twinapex/parts/zope2/lib/python/zope/configuration/config.py", line 1383, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/moo/twinapex/parts/zope2/lib/python/zope/configuration/fields.py", line 141, in fromUnicode
    raise schema.ValidationError(v)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/moo/twinapex/parts/instance/etc/site.zcml", line 14.2-14.55
    ZopeXMLConfigurationError: File "/Users/moo/twinapex/parts/instance/etc/package-includes/009-gomobile.mobile-configure.zcml", line 1.0-1.59
    ZopeXMLConfigurationError: File "/Users/moo/twinapex/src/gomobile.mobile/gomobile/mobile/configure.zcml", line 15.4-15.51
    ZopeXMLConfigurationError: File "/Users/moo/twinapex/eggs/plone.postpublicationhook-1.1-py2.4.egg/plone/postpublicationhook/configure.zcml", line 5.4-8.10
    ConfigurationError: ('Invalid value for', 'package', "ImportError: Couldn't import ZPublisherEventsBackport, No module named ZPublisherEventsBackport")</pre>
</div>
<p>plone.postpublicationhook 1.1 depends on new package, ZPublisherEventsBackport, for Plone 3.3. You eed to include
them both in your buildout. You need to include both eggs:</p>
<div class="highlight-python"><pre>eggs =
        ZPublisherEventsBackport
        plone.postpublicationhook</pre>
</div>
</div>
<div class="section" id="error-zodb-connection-couldn-t-load-state-for-0x00">
<h2><a class="toc-backref" href="#id26">ERROR ZODB.Connection Couldn't load state for 0x00</a><a class="headerlink" href="#error-zodb-connection-couldn-t-load-state-for-0x00" title="Permalink to this headline">Â¶</a></h2>
<p>The following traceback pops up when you try to start Zope:</p>
<div class="highlight-python"><pre>2010-07-14 05:02:33 ERROR ZODB.Connection Couldn't load state for 0x00
Traceback (most recent call last):
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/Connection.py", line 811, in setstate
    self._setstate(obj)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/Connection.py", line 870, in _setstate
    self._reader.setGhostState(obj, p)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/serialize.py", line 604, in setGhostState
    state = self.getState(pickle)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/serialize.py", line 597, in getState
    return unpickler.load()
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/serialize.py", line 471, in _persistent_load
    return self.load_oid(reference)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/serialize.py", line 537, in load_oid
    return self._conn.get(oid)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/Connection.py", line 244, in get
    p, serial = self._storage.load(oid, self._version)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/FileStorage/FileStorage.py", line 470, in load
    pos = self._lookup_pos(oid)
  File "/Users/moo/yourinstance/eggs/ZODB3-3.8.4-py2.4-macosx-10.6-i386.egg/ZODB/FileStorage/FileStorage.py", line 462, in _lookup_pos
    raise POSKeyError(oid)
POSKeyError: 0x01</pre>
</div>
<p>Data.fs might have been damaged. You might be using blobs with Plone 3 and they don't work perfectly.
. . . or a bunch other issues which generally mean that your day is screwed.</p>
<p>See also</p>
<ul class="simple">
<li><a class="reference external" href="http://plonechix.blogspot.com/2009/12/definitive-guide-to-poskeyerror.html">http://plonechix.blogspot.com/2009/12/definitive-guide-to-poskeyerror.html</a></li>
</ul>
</div>
<div class="section" id="poskeyerror">
<h2><a class="toc-backref" href="#id27">POSKeyError</a><a class="headerlink" href="#poskeyerror" title="Permalink to this headline">Â¶</a></h2>
<p>POSKeyError is when the database has been unable to convert a reference to an object into the object itself
It's a low level error usually caused by a corrupt or incomplete database.</p>
</div>
<div class="section" id="zope-suddenly-dies-on-osx-without-a-reason">
<h2><a class="toc-backref" href="#id28">Zope suddenly dies on OSX without a reason</a><a class="headerlink" href="#zope-suddenly-dies-on-osx-without-a-reason" title="Permalink to this headline">Â¶</a></h2>
<p>Symptoms: you do a HTTP request to a Plone site running OSX. Zope quits without a reason.</p>
<p>Reason: Infinite recursion is not properly handled by Python on OSX. This is because
OSX C stack size is smaller than Python default stack size. The underlying Python interpreter
dies before being able to raise stack size limit exception.</p>
<p><strong>Workaround</strong></p>
<p>Edit <tt class="docutils literal"><span class="pre">python-2.4/lib/python2.4/site.py</span></tt> or corresponding Python interpreter <tt class="docutils literal"><span class="pre">site.py</span></tt>
file (Python site installation customization file).</p>
<p>Put in to the first code line:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">sys</span><span class="o">.</span><span class="n">setrecursionlimit</span><span class="p">(</span><span class="mi">800</span><span class="p">)</span>
</pre></div>
</div>
<p>This will force smaller Python stack not exceeding native OSX C stack.
You might want to test other values and report back the findings.</p>
<p>More Information</p>
<ul class="simple">
<li><a class="reference external" href="http://blog.crowproductions.de/2008/12/14/a-buildout-to-tame-the-snake-pit/">http://blog.crowproductions.de/2008/12/14/a-buildout-to-tame-the-snake-pit/</a> (comments)</li>
</ul>
</div>
<div class="section" id="ioerror-errno-url-error-unknown-url-type-https">
<h2><a class="toc-backref" href="#id29">IOError: [Errno url error] unknown url type: 'https'</a><a class="headerlink" href="#ioerror-errno-url-error-unknown-url-type-https" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>  File "/home/moo/code/python/parts/opt/lib/python2.4/urllib.py", line 89, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/home/moo/code/python/parts/opt/lib/python2.4/urllib.py", line 222, in retrieve
    fp = self.open(url, data)
  File "/home/moo/code/python/parts/opt/lib/python2.4/urllib.py", line 187, in open
    return self.open_unknown(fullurl, data)
  File "/home/moo/code/python/parts/opt/lib/python2.4/urllib.py", line 199, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'https'</pre>
</div>
<p>Reason: Python and Python socket modules have not been compiled with SSL support.</p>
<p>Make sure that you have SSL development libraries installed (Ubuntu/Debian example)</p>
<div class="highlight-console"><div class="highlight"><pre><span class="go">sudo apt-get install libssl-dev</span>
</pre></div>
</div>
<p>Make sure that Python is built with SSL support</p>
<div class="highlight-console"><div class="highlight"><pre><span class="go">./configure --with-package=_ssl</span>
</pre></div>
</div>
<p>You can test Python after compilation:</p>
<div class="highlight-python"><pre>moo@murskaamo:~/code/python$ source python-2.4/bin/activate
(python-2.4)moo@murskaamo:~/code/python$ python
Python 2.4.6 (#1, Jul 16 2010, 10:31:46)
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import _ssl
&gt;&gt;&gt;</pre>
</div>
<p>Also you might want try</p>
<div class="highlight-console"><div class="highlight"><pre><span class="go">easy_install pyopenssl</span>
</pre></div>
</div>
</div>
<div class="section" id="typeerror-len-of-unsized-object-in-smtplib">
<h2><a class="toc-backref" href="#id30">TypeError: len() of unsized object in smtplib</a><a class="headerlink" href="#typeerror-len-of-unsized-object-in-smtplib" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback:</p>
<div class="highlight-python"><pre>Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 90, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 28, in _call
  Module Products.CMFFormController.ControllerBase, line 231, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 104, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 140, in __call__
  Module Shared.DC.Scripts.Bindings, line 313, in __call__
  Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
  Module Products.CMFCore.FSPythonScript, line 196, in _exec
  Module None, line 102, in order_email
   - &lt;FSControllerPythonScript at /MySite/order_email&gt;
   - Line 102
  Module Products.SecureMailHost.SecureMailHost, line 246, in secureSend
  Module Products.SecureMailHost.SecureMailHost, line 276, in _send
  Module Products.SecureMailHost.mail, line 126, in send
  Module smtplib, line 576, in login
  Module smtplib, line 536, in encode_cram_md5
  Module hmac, line 50, in __init__
TypeError: len() of unsized object</pre>
</div>
<p>Cause: Your SMTP password has been set empty. Please reset your SMTP password in <em>Mail</em> control panel.</p>
<p>More information</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.293351.n2.nabble.com/Plone-3-3-5-sending-emails-len-of-unsized-object-error-NO-ESMTP-PASSWORD-tp5415484p5415484.html">http://plone.293351.n2.nabble.com/Plone-3-3-5-sending-emails-len-of-unsized-object-error-NO-ESMTP-PASSWORD-tp5415484p5415484.html</a></li>
</ul>
</div>
<div class="section" id="nameerror-name-test-is-not-defined">
<h2><a class="toc-backref" href="#id31">NameError: name 'test' is not defined</a><a class="headerlink" href="#nameerror-name-test-is-not-defined" title="Permalink to this headline">Â¶</a></h2>
<p>This exception occurs when you try to customize TAL page template code using test() function.
test() function has been dropped in Zope 3 page templates. You should no longer
use test() function anywhere.</p>
<p>Solution: replace test() with common Python expression in your customized template.</p>
<p>For example the orignal:</p>
<div class="highlight-python"><pre>tal:attributes="class python:test(here.Format() in ('text/structured', 'text/x-rst', ), 'stx' + kss_class, 'plain', + kss_class)"</pre>
</div>
<p>would need to be written as:</p>
<blockquote>
tal:attributes=&quot;class python:here.Format() in ('text/structured', 'text/x-rst', ) 'stx' + kss_class and 'plain' or kss_class&quot;</blockquote>
</div>
<div class="section" id="traversalerror-subject-name-in-expressions">
<h2><a class="toc-backref" href="#id32">TraversalError(subject, name) in expressions</a><a class="headerlink" href="#traversalerror-subject-name-in-expressions" title="Permalink to this headline">Â¶</a></h2>
<p>You have traceback like:</p>
<div class="highlight-python"><pre>File "/home/moo/sits/parts/zope2/lib/python/ZPublisher/Publish.py", line 119, in publish
  request, bind=1)
File "/home/moo/sits/parts/zope2/lib/python/ZPublisher/mapply.py", line 88, in mapply
  if debug is not None: return debug(object,args,context)
File "/home/moo/sits/parts/zope2/lib/python/ZPublisher/Publish.py", line 42, in call_object
  result=apply(object,args) # Type s&lt;cr&gt; to step into published object.
File "/home/moo/sits/parts/zope2/lib/python/Products/Five/browser/metaconfigure.py", line 417, in __call__
  return self.index(self, *args, **kw)
File "/home/moo/sits/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 313, in __call__
  return self._bindAndExec(args, kw, None)
File "/home/moo/sits/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 350, in _bindAndExec
  return self._exec(bound_data, args, kw)
File "/home/moo/sits/parts/zope2/lib/python/Products/PageTemplates/PageTemplateFile.py", line 129, in _exec
  return self.pt_render(extra_context=bound_names)
File "/home/moo/sits/parts/zope2/lib/python/Products/PageTemplates/PageTemplate.py", line 98, in pt_render
  showtal=showtal)
File "/home/moo/sits/parts/zope2/lib/python/zope/pagetemplate/pagetemplate.py", line 117, in pt_render
  strictinsert=0, sourceAnnotations=sourceAnnotations)()
File "/home/moo/sits/parts/zope2/lib/python/zope/tal/talinterpreter.py", line 271, in __call__
  self.interpret(self.program)
File "/home/moo/sits/parts/zope2/lib/python/zope/tal/talinterpreter.py", line 346, in interpret
  handlers[opcode](self, args)
File "/home/moo/sits/parts/zope2/lib/python/zope/tal/talinterpreter.py", line 891, in do_useMacro
  self.interpret(macro)
  handlers[opcode](self, args)

...

File "/home/moo/sits/parts/zope2/lib/python/zope/tal/talinterpreter.py", line 586, in do_setLocal_tal
  self.engine.setLocal(name, self.engine.evaluateValue(expr))
File "/home/moo/sits/parts/zope2/lib/python/zope/tales/tales.py", line 696, in evaluate
  return expression(self)
File "/home/moo/sits/parts/zope2/lib/python/zope/tales/expressions.py", line 218, in __call__
  return self._eval(econtext)
File "/home/moo/sits/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 153, in _eval
  ob = self._subexprs[-1](econtext)
File "/home/moo/sits/parts/zope2/lib/python/zope/tales/expressions.py", line 124, in _eval
  ob = self._traverser(ob, element, econtext)
File "/home/moo/sits/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 103, in trustedBoboAwareZopeTraverse
  request=request)
File "/home/moo/sits/parts/zope2/lib/python/zope/traversing/adapters.py", line 164, in traversePathElement
  return traversable.traverse(nm, further_path)
File "/home/moo/sits/parts/zope2/lib/python/zope/traversing/adapters.py", line 52, in traverse
  raise TraversalError(subject, name)</pre>
</div>
<p>From line <tt class="docutils literal"><span class="pre">Products/PageTemplates/Expressions.py</span></tt> you can see the error comes from TAL templates.
TAL templates are trying to execute path based expressions.</p>
<p>If you can view this error through error_log the error_log traceback will contain information
what expression causes the exception. However if this only happens with unit tests you can have something like:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">__call__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">econtext</span><span class="p">):</span>
    <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_name</span> <span class="o">==</span> <span class="s">&#39;exists&#39;</span><span class="p">:</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_exists</span><span class="p">(</span><span class="n">econtext</span><span class="p">)</span>
    <span class="k">print</span> <span class="s">&quot;Evaluating expression:&quot;</span> <span class="o">+</span> <span class="bp">self</span><span class="o">.</span><span class="n">_s</span>
    <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_eval</span><span class="p">(</span><span class="n">econtext</span><span class="p">)</span>
</pre></div>
</div>
<p>manually injected to <tt class="docutils literal"><span class="pre">zope.tales.expression</span></tt> module.</p>
</div>
<div class="section" id="content-status-history-won-t-render-traceback-is-content-path-reversed">
<h2><a class="toc-backref" href="#id33">Content status history won't render - traceback is content path reversed</a><a class="headerlink" href="#content-status-history-won-t-render-traceback-is-content-path-reversed" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback:</p>
<div class="highlight-python"><pre>  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/home/antti/workspace/plone/hotellilevitunturi/eggs/Plone-3.3.5-py2.4.egg/Products/CMFPlone/skins/plone_forms/content_status_history.cpt
   - Line 201, Column 14
   - Expression: &lt;PythonExpr wtool.getTransitionsFor(target, here)&gt;
   - Names:
      {'container': &lt;PloneSite at /hotellilevitunturi&gt;,
       'context': &lt;MainFolder at /hotellilevitunturi/fi/ravintolamaailma&gt;,
       'default': &lt;object object at 0xb75d2540&gt;,
       'here': &lt;MainFolder at /hotellilevitunturi/fi/ravintolamaailma&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': (),
                   'state': &lt;Products.CMFFormController.ControllerState.ControllerState object at 0x1055614c&gt;},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0x10556f6c&gt;,
       'request': &lt;HTTPRequest, URL=http://localhost:9888/hotellilevitunturi/fi/ravintolamaailma/content_status_history&gt;,
       'root': &lt;Application at &gt;,
       'template': &lt;FSControllerPageTemplate at /hotellilevitunturi/content_status_history used for /hotellilevitunturi/fi/ravintolamaailma&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;}
  Module Products.PageTemplates.ZRPythonExpr, line 49, in __call__
   - __traceback_info__: wtool.getTransitionsFor(target, here)
  Module PythonExpr, line 1, in &lt;expression&gt;
  Module Products.CMFPlone.WorkflowTool, line 88, in getTransitionsFor
  Module Products.CMFPlone.WorkflowTool, line 37, in flattenTransitions
  Module Products.CMFPlone.WorkflowTool, line 69, in flattenTransitionsForPaths
  Module OFS.Traversable, line 301, in restrictedTraverse
  Module OFS.Traversable, line 284, in unrestrictedTraverse
   - __traceback_info__: ([u's', u'a', u'n', u'u', u'o', u'l', u'/', u'a', u'm', u'l', u'i', u'a', u'a', u'm', u'a', u'l', u'o', u't', u'n', u'i', u'v', u'a', u'r', u'/', u'i', u'f', u'/', u'i', u'r', u'u', u't', u'n', u'u', u't', u'i', u'v', u'e', u'l', u'i', u'l', u'l', u'e', u't', u'o', u'h'], u'/')
KeyError: u'/'</pre>
</div>
<p>TODO: No solution</p>
</div>
<div class="section" id="attributeerror-module-object-has-no-attribute-httpsconnection">
<h2><a class="toc-backref" href="#id34">AttributeError: 'module' object has no attribute 'HTTPSConnection'</a><a class="headerlink" href="#attributeerror-module-object-has-no-attribute-httpsconnection" title="Permalink to this headline">Â¶</a></h2>
<p>Python has not been compiled with HTTPS support.</p>
<p>Try installing your Python, for example, using minitage.</p>
<p>See <a class="reference internal" href="../tutorials/python.html"><em>Python basics</em></a>.</p>
</div>
<div class="section" id="linguaplone-importerror-cannot-import-name-permissions">
<h2><a class="toc-backref" href="#id35">LinguaPlone: ImportError: cannot import name permissions</a><a class="headerlink" href="#linguaplone-importerror-cannot-import-name-permissions" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback:</p>
<div class="highlight-python"><pre>  File "/home/moo/code/finnmall/finnmall/src/abita.theme/abita/theme/browser/viewlets/selector.py", line 12, in &lt;module&gt;
    from Products.LinguaPlone.interfaces import ITranslatable
  File "/home/moo/code/finnmall/finnmall/eggs/Products.LinguaPlone-3.1-py2.6.egg/Products/LinguaPlone/__init__.py", line 3, in &lt;module&gt;
    from Products.LinguaPlone import permissions
ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/parts/instance/etc/site.zcml", line 15.2-15.55
    ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/parts/instance/etc/package-includes/001-abita.policy-configure.zcml", line 1.0-1.56
    ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/src/abita.policy/abita/policy/configure.zcml", line 8.4-8.37
    ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/src/abita.theme/abita/theme/configure.zcml", line 9.2-9.32
    ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/src/abita.theme/abita/theme/browser/configure.zcml", line 10.2-10.33
    ZopeXMLConfigurationError: File "/home/moo/code/finnmall/finnmall/src/abita.theme/abita/theme/browser/viewlets/configure.zcml", line 6.2-11.6
    ImportError: cannot import name permissions</pre>
</div>
<p>This seems to be Plone 4 issue of some sort.
Import Products.ATContentTypes before importing LinguagePlone.</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.org/products/linguaplone/issues/253">http://plone.org/products/linguaplone/issues/253</a></li>
</ul>
<p>Related</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.org/products/linguaplone/issues/253">http://plone.org/products/linguaplone/issues/253</a></li>
</ul>
</div>
<div class="section" id="typeerror-nonetype-object-is-not-callable">
<h2><a class="toc-backref" href="#id36">TypeError: 'NoneType' object is not callable</a><a class="headerlink" href="#typeerror-nonetype-object-is-not-callable" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback during add-on install run:</p>
<div class="highlight-python"><pre>Traceback (innermost last):
  Module ZPublisherEventsBackport.patch, line 77, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 589, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 526, in installProduct
   - __traceback_info__: ('mfabrik.plonezohointegration',)
  Module Products.GenericSetup.tool, line 390, in runAllImportStepsFromProfile
   - __traceback_info__: profile-mfabrik.plonezohointegration:default
  Module Products.GenericSetup.tool, line 1179, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1090, in _doRunImportStep
   - __traceback_info__: toolset
  Module Products.GenericSetup.tool, line 128, in importToolset
TypeError: 'NoneType' object is not callable</pre>
</div>
<p>More pointers:</p>
<div class="highlight-python"><pre>(Pdb) tool_id
'portal_newsletters'</pre>
</div>
<p>This happens when you have used Singing and Dancing news letter product. This add-on
is problematic and does not uninstall cleanly.</p>
<ul class="simple">
<li>Reinstall Singing &amp; Dancing</li>
<li>Uninstall Singing &amp; Dancing</li>
<li>Hope your site works again</li>
</ul>
<p>Or try</p>
<ul class="simple">
<li><a class="reference external" href="http://pypi.python.org/pypi/wildcard.fixpersistentutilities">http://pypi.python.org/pypi/wildcard.fixpersistentutilities</a></li>
</ul>
</div>
<div class="section" id="importerror-no-module-named-pkgutil">
<h2><a class="toc-backref" href="#id37">ImportError: No module named pkgutil</a><a class="headerlink" href="#importerror-no-module-named-pkgutil" title="Permalink to this headline">Â¶</a></h2>
<p>Example:</p>
<div class="highlight-python"><pre>Traceback (most recent call last):
  File "/Users/moo/plonecommunity/bin/idelauncher.py", line 101, in &lt;module&gt;
    exec(data, globals())
  File "&lt;string&gt;", line 543, in &lt;module&gt;
  File "/Users/moo/plonecommunity/eggs/plone.app.z3cform-0.5.0-py2.6.egg/plone/__init__.py", line 5, in &lt;module&gt;
    from pkgutil import extend_path
ImportError: No module named pkgutil</pre>
</div>
<p>If you are using Eclipse, <tt class="docutils literal"><span class="pre">idelauncher.py</span></tt> has been updated for Plone 4.</p>
<ul class="simple">
<li>Remove <tt class="docutils literal"><span class="pre">bin/idelauncher.py</span></tt> from file system</li>
<li>Redownload it from <a class="reference external" href="http://plone.org/documentation/kb/developing-plone-with-eclipse/ide-compatible-launcher-script">here</a></li>
<li>...or of you are using <em>collective.eclipsescripts</em> rerun command <em>Scripts -&gt; Plone -&gt; Import src folder as workspace</em></li>
</ul>
</div>
<div class="section" id="picklingerror-can-t-pickle-class-collective-singing-async-iqueue-import-of-module-collective-singing-async">
<h2><a class="toc-backref" href="#id38">&quot;PicklingError: Can't pickle &lt;class 'collective.singing.async.IQueue'&gt;: import of module collective.singing.async&quot;</a><a class="headerlink" href="#picklingerror-can-t-pickle-class-collective-singing-async-iqueue-import-of-module-collective-singing-async" title="Permalink to this headline">Â¶</a></h2>
<p>Singing &amp; Dancing add-on does not uninstall cleanly. Try this command-line script to get it fixed (not tested).
Some parts may work, some not, depending on how messed up your site is.</p>
<p>Note that you need to have S &amp; D present in the buildout when running this and
then you can remove it afterwards:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">transaction</span>
<span class="kn">from</span> <span class="nn">collective.singing.interfaces</span> <span class="kn">import</span> <span class="n">ISalt</span>
<span class="kn">from</span> <span class="nn">collective.singing.async</span> <span class="kn">import</span> <span class="n">IQueue</span>

<span class="c"># Your site here</span>
<span class="n">portal</span> <span class="o">=</span> <span class="n">app</span><span class="o">.</span><span class="n">mfabrik</span>
<span class="n">sm</span> <span class="o">=</span> <span class="n">portal</span><span class="o">.</span><span class="n">getSiteManager</span><span class="p">()</span>

<span class="n">util_obj</span> <span class="o">=</span> <span class="n">sm</span><span class="o">.</span><span class="n">getUtility</span><span class="p">(</span><span class="n">ISalt</span><span class="p">)</span>
<span class="n">sm</span><span class="o">.</span><span class="n">unregisterUtility</span><span class="p">(</span><span class="n">provided</span><span class="o">=</span><span class="n">ISalt</span><span class="p">)</span>
<span class="k">del</span> <span class="n">util_obj</span>

<span class="n">sm</span><span class="o">.</span><span class="n">utilities</span><span class="o">.</span><span class="n">unsubscribe</span><span class="p">((),</span> <span class="n">ISalt</span><span class="p">)</span>
<span class="k">del</span> <span class="n">sm</span><span class="o">.</span><span class="n">utilities</span><span class="o">.</span><span class="n">__dict__</span><span class="p">[</span><span class="s">&#39;_provided&#39;</span><span class="p">][</span><span class="n">ISalt</span><span class="p">]</span>
<span class="k">del</span> <span class="n">sm</span><span class="o">.</span><span class="n">utilities</span><span class="o">.</span><span class="n">_subscribers</span><span class="p">[</span><span class="mi">0</span><span class="p">][</span><span class="n">ISalt</span><span class="p">]</span>

<span class="n">util</span> <span class="o">=</span> <span class="n">sm</span><span class="o">.</span><span class="n">queryUtility</span><span class="p">(</span><span class="n">IQueue</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="s">&#39;collective.dancing.jobs&#39;</span><span class="p">)</span>
<span class="n">sm</span><span class="o">.</span><span class="n">unregisterUtility</span><span class="p">(</span><span class="n">util</span><span class="p">,</span> <span class="n">IQueue</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="s">&#39;collective.dancing.jobs&#39;</span><span class="p">)</span>
<span class="k">del</span> <span class="n">util</span>
<span class="k">del</span> <span class="n">sm</span><span class="o">.</span><span class="n">utilities</span><span class="o">.</span><span class="n">_subscribers</span><span class="p">[</span><span class="mi">0</span><span class="p">][</span><span class="n">IQueue</span><span class="p">]</span>

<span class="n">transaction</span><span class="o">.</span><span class="n">commit</span><span class="p">()</span>
</pre></div>
</div>
</div>
<div class="section" id="system-lxml-too-old">
<h2><a class="toc-backref" href="#id39">System lxml too old</a><a class="headerlink" href="#system-lxml-too-old" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback when starting an instance:</p>
<div class="highlight-python"><pre>from lxml.html import defs
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/srv/plone/yourinstance/parts/client1/etc/site.zcml", line 14.2-14.55
ZopeXMLConfigurationError: File "/srv/plone/yourinstance/parts/client1/etc/package-includes/012-yourinstance.mobi-configure.zcml", line 1.0-1.59
ZopeXMLConfigurationError: File "/srv/plone/yourinstance/src/yourinstance.mobi/yourinstance/mobi/configure.zcml", line 13.2-13.43
ZopeXMLConfigurationError: File "/srv/plone/yourinstance/src/gomobiletheme.basic/gomobiletheme/basic/configure.zcml", line 16.2-16.39
ZopeXMLConfigurationError: File "/srv/plone/yourinstance/src/gomobile.mobile/gomobile/mobile/configure.zcml", line 19.4-19.34
ZopeXMLConfigurationError: File "/srv/plone/yourinstance/src/gomobile.mobile/gomobile/mobile/browser/configure.zcml", line 24.4-29.10
ImportError: No module named html</pre>
</div>
<p>Let's see if we are getting too old system wide lxml installation:</p>
<div class="highlight-python"><pre>plone@mansikki:/srv/plone/yourinstance$ python2.4
Python 2.4.5 (#2, Jan 21 2010, 20:05:55)
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import lxml
&gt;&gt;&gt; lxml.__file__
'/usr/lib/python2.4/site-packages/lxml/__init__.pyc'
&gt;&gt;&gt; dir(lxml)
['__builtins__', '__doc__', '__file__', '__name__', '__path__']
&gt;&gt;&gt; from lxml import html
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in ?
ImportError: cannot import name html</pre>
</div>
<p>If we cannot fix the system lxml (your system software depends on it) the only workaround is to
create virtualenv. We cannot force Python 2.6, 2.5 or 2.4 not to use system libraries.</p>
<p>Example:</p>
<div class="highlight-python"><pre>root@mansikki:/srv/plone# virtualenv -p /usr/bin/python2.4 --no-site-packages py24</pre>
</div>
<p>Include standalone lxml + libxml compilation in your <tt class="docutils literal"><span class="pre">buildout.cfg</span></tt>:</p>
<div class="highlight-python"><pre>parts =
        ...
        lxml

[lxml]
recipe = z3c.recipe.staticlxml
egg = lxml==2.2.6
force = false</pre>
</div>
<p>If there are exiting lxml builds in buildout be sure they are removed:</p>
<div class="highlight-python"><pre>rm -rf eggs/lxml*</pre>
</div>
<p>Then as the non-root re-bootstrap the buildout using non-system wide Python:</p>
<div class="highlight-python"><pre>plone@mansikki:/srv/plone/yourinstance-2010/yourinstance$ source /srv/plone/py24/bin/activate
(py24)plone@mansikki:/srv/plone/yourinstance-2010/yourinstance$ python bootstrap.py
...
(py24)plone@mansikki:/srv/plone/yourinstance-2010/yourinstance$ bin/buildout
...</pre>
</div>
<p>... and after this it should no longer pull the bad system lxml.</p>
</div>
<div class="section" id="traversalerror-standard-macros">
<h2><a class="toc-backref" href="#id40">TraversalError: &#64;&#64;standard_macros</a><a class="headerlink" href="#traversalerror-standard-macros" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback:</p>
<div class="highlight-python"><pre>   - Warning: Macro expansion failed
   - Warning: zope.traversing.interfaces.TraversalError: (&lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;, '++view++standard_macros')
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 346, in interpret
  Module zope.tal.talinterpreter, line 870, in do_useMacro
  Module zope.tales.tales, line 696, in evaluate
   - URL: form
   - Line 1, Column 0
   - Expression: &lt;PathExpr standard:'context/@@standard_macros/page'&gt;
   - Names:
      {'container': &lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;,
       'context': &lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;,
       'default': &lt;object object at 0x100311200&gt;,
       'here': &lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;,
       'loop': {},
       'nothing': None,
       'options': {'args': (&lt;plone.app.headeranimation.browser.forms.AddHeaderAnimationForm object at 0x1102dc490&gt;,)},
       'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0x110845758&gt;,
       'request': None,
       'root': None,
       'template': &lt;ImplicitAcquirerWrapper object at 0x11084ff10&gt;,
       'traverse_subpath': [],
       'user': &lt;PropertiedUser 'admin'&gt;,
       'view': &lt;UnauthorizedBinding: context&gt;,
       'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0x110844310&gt;}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 105, in trustedBoboAwareZopeTraverse
  Module zope.traversing.adapters, line 154, in traversePathElement
   - __traceback_info__: (&lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;, '@@standard_macros')
  Module zope.traversing.namespace, line 107, in namespaceLookup
TraversalError: (&lt;plone.app.headeranimation.browser.forms.HeaderCRUDForm object at 0x110289590&gt;, '++view++standard_macros')</pre>
</div>
<p>:doc`Wrapping is missing from your form object &lt;/forms/z3c.form.txt&gt;`.
In this case the following helped:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">update</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
    <span class="nb">super</span><span class="p">(</span><span class="n">HeaderCRUDForm</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="n">update</span><span class="p">()</span>

    <span class="n">addform</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">addform_factory</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">request</span><span class="p">)</span>
    <span class="n">editform</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">editform_factory</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">request</span><span class="p">)</span>

    <span class="kn">import</span> <span class="nn">zope.interface</span>
    <span class="kn">from</span> <span class="nn">plone.z3cform.interfaces</span> <span class="kn">import</span> <span class="n">IWrappedForm</span>

    <span class="n">zope</span><span class="o">.</span><span class="n">interface</span><span class="o">.</span><span class="n">alsoProvides</span><span class="p">(</span><span class="n">addform</span><span class="p">,</span> <span class="n">IWrappedForm</span><span class="p">)</span>
    <span class="n">addform</span><span class="o">.</span><span class="n">update</span><span class="p">()</span>
    <span class="n">editform</span><span class="o">.</span><span class="n">update</span><span class="p">()</span>
    <span class="bp">self</span><span class="o">.</span><span class="n">subforms</span> <span class="o">=</span> <span class="p">[</span><span class="n">editform</span><span class="p">,</span> <span class="n">addform</span><span class="p">]</span>
</pre></div>
</div>
</div>
<div class="section" id="attributeerror-wrapper-descriptor-object-has-no-attribute-im-func">
<h2><a class="toc-backref" href="#id41">AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'</a><a class="headerlink" href="#attributeerror-wrapper-descriptor-object-has-no-attribute-im-func" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback when starting Plone:</p>
<div class="highlight-python"><pre>  File "/home/moo/code/gomobile/parts/zope2/lib/python/DocumentTemplate/DT_Util.py", line 19, in &lt;module&gt;
    from html_quote import html_quote, ustr # for import by other modules, dont remove!
  File "/home/moo/code/gomobile/parts/zope2/lib/python/DocumentTemplate/html_quote.py", line 4, in &lt;module&gt;
    from ustr import ustr
  File "/home/moo/code/gomobile/parts/zope2/lib/python/DocumentTemplate/ustr.py", line 18, in &lt;module&gt;
    nasty_exception_str = Exception.__str__.im_func
AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'</pre>
</div>
<p>Cause: Trying to use Python 2.6 with Plone 3 - you need to use Python 2.4.</p>
</div>
<div class="section" id="getutility-fails-componentlookuperror">
<h2><a class="toc-backref" href="#id42">getUtility() fails: ComponentLookupError</a><a class="headerlink" href="#getutility-fails-componentlookuperror" title="Permalink to this headline">Â¶</a></h2>
<p>Example exception:</p>
<div class="highlight-python"><pre>-&gt; filter = getUtility(IConvergenceMediaFilter)
(Pdb) n
ComponentLookupError: &lt;zope.component.interfaces.ComponentLookupError instance at 0x1038166c&gt;</pre>
</div>
<p>Make sure that your class object implements in the utility interface in the question:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">ConvergedMediaFilter</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="n">zope</span><span class="o">.</span><span class="n">interface</span><span class="o">.</span><span class="n">implements</span><span class="p">(</span><span class="n">IConvergenceMediaFilter</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="section" id="attributeerror-request-in-getobject">
<h2><a class="toc-backref" href="#id43">AttributeError: REQUEST in getObject</a><a class="headerlink" href="#attributeerror-request-in-getobject" title="Permalink to this headline">Â¶</a></h2>
<p>Traceback:</p>
<div class="highlight-python"><pre>  import ZPublisher, Zope
Traceback (most recent call last):
  File "&lt;string&gt;", line 1, in ?
  File "src/collective.mountpoint/collective/mountpoint/bin/update.py", line 31, in ?
    sys.exit(main(app))
  File "/srv/plone/saariselka/src/collective.mountpoint/collective/mountpoint/updateclient.py", line 243, in main
    exit_code = updater.updateAll()
  File "/srv/plone/saariselka/src/collective.mountpoint/collective/mountpoint/updateclient.py", line 151, in updateAll
    mountpoints = list(self.getMountPoints())
  File "/srv/plone/saariselka/src/collective.mountpoint/collective/mountpoint/updateclient.py", line 49, in getMountPoints
    return [ brain.getObject() for brain in brains ]
  File "/srv/plone/saariselka/parts/zope2/lib/python/Products/ZCatalog/CatalogBrains.py", line 86, in getObject
    target = parent.restrictedTraverse(path[-1])
  File "/srv/plone/saariselka/parts/zope2/lib/python/OFS/Traversable.py", line 301, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "/srv/plone/saariselka/parts/zope2/lib/python/OFS/Traversable.py", line 259, in unrestrictedTraverse
    next = queryMultiAdapter((obj, self.REQUEST),
AttributeError: REQUEST</pre>
</div>
<p>Reason: You are using command line script. getObject() fails for a catalog brain, because the actual object
is gone. However, unrestrictedTraverse() does not handle this case gracefully.</p>
</div>
<div class="section" id="get-language-nonetype-object-has-no-attribute-getlocaleid">
<h2><a class="toc-backref" href="#id44">get_language: 'NoneType' object has no attribute 'getLocaleID'</a><a class="headerlink" href="#get-language-nonetype-object-has-no-attribute-getlocaleid" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>Traceback (innermost last):

    Module ZPublisher.Publish, line 202, in publish_module_standard
    Module ZPublisherEventsBackport.patch, line 115, in publish
    Module plone.app.linkintegrity.monkey, line 21, in zpublisher_exception_hook_wrapper
    Module Zope2.App.startup, line 221, in zpublisher_exception_hook
    Module ZPublisherEventsBackport.patch, line 77, in publish
    Module ZPublisher.mapply, line 88, in mapply
    Module ZPublisher.Publish, line 42, in call_object
    Module Products.Five.browser.metaconfigure, line 417, in __call__
    Module Shared.DC.Scripts.Bindings, line 313, in __call__
    Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
    Module Products.PageTemplates.PageTemplateFile, line 129, in _exec
    Module Products.CacheSetup.patch_cmf, line 126, in PT_pt_render
    Warning: Macro expansion failed
    Warning: exceptions.TypeError: ('Could not adapt', &lt;HTTPRequest, URL=http://mansikki.redinnovation.com:9666/isleofback/sisalto/etusivu/isleofbackfrontpage_view&gt;, &lt;InterfaceClass zope.i18n.interfaces.IUserPreferredLanguages&gt;)
    Module zope.tal.talinterpreter, line 271, in __call__
    Module zope.tal.talinterpreter, line 346, in interpret
    Module zope.tal.talinterpreter, line 891, in do_useMacro
    Module zope.tal.talinterpreter, line 346, in interpret
    Module zope.tal.talinterpreter, line 536, in do_optTag_tal
    Module zope.tal.talinterpreter, line 521, in do_optTag
    Module zope.tal.talinterpreter, line 516, in no_tag
    Module zope.tal.talinterpreter, line 346, in interpret
    Module zope.tal.talinterpreter, line 534, in do_optTag_tal
    Module zope.tal.talinterpreter, line 516, in no_tag
    Module zope.tal.talinterpreter, line 346, in interpret
    Module zope.tal.talinterpreter, line 745, in do_insertStructure_tal
    Module Products.PageTemplates.Expressions, line 223, in evaluateStructure
    Module zope.tales.tales, line 696, in evaluate
    URL: file:/srv/plone/saariselka.fi/src/plonetheme.isleofback/plonetheme/isleofback/skins/plonetheme_isleofback_custom_templates/main_template.pt
    Line 58, Column 4
    Expression: &lt;StringExpr u'plone.htmlhead.links'&gt;
    Names:

    {'container': &lt;IsleofbackFrontpage at /isleofback/sisalto/etusivu&gt;,
     'context': &lt;IsleofbackFrontpage at /isleofback/sisalto/etusivu&gt;,
     'default': &lt;object object at 0x7fd445785220&gt;,
     'here': &lt;IsleofbackFrontpage at /isleofback/sisalto/etusivu&gt;,
     'loop': {},
     'nothing': None,
     'options': {'args': (&lt;Products.Five.metaclass.SimpleViewClass from /srv/plone/saariselka.fi/src/isleofback.app/isleofback/app/browser/isleofbacknewfrontpageview.pt object at 0xbaa9910&gt;,)},
     'repeat': &lt;Products.PageTemplates.Expressions.SafeMapping object at 0xcd1b3f8&gt;,
     'request': &lt;HTTPRequest, URL=http://mansikki.redinnovation.com:9666/isleofback/sisalto/etusivu/isleofbackfrontpage_view&gt;,
     'root': &lt;Application at &gt;,
     'template': &lt;ImplicitAcquirerWrapper object at 0xcd208d0&gt;,
     'traverse_subpath': [],
     'user': &lt;SpecialUser 'Anonymous User'&gt;,
     'view': &lt;Products.Five.metaclass.SimpleViewClass from /srv/plone/saariselka.fi/src/isleofback.app/isleofback/app/browser/isleofbacknewfrontpageview.pt object at 0xbaa9910&gt;,
     'views': &lt;zope.app.pagetemplate.viewpagetemplatefile.ViewMapper object at 0xcd20d90&gt;}

    Module Products.Five.browser.providerexpression, line 37, in __call__
    Module plone.app.viewletmanager.manager, line 83, in render
    Module plone.memoize.volatile, line 265, in replacement
    Module plone.app.layout.links.viewlets, line 28, in render_cachekey
    Module plone.app.layout.links.viewlets, line 19, in get_language

AttributeError: &lt;exceptions.AttributeError instance at 0xcd1bb48&gt; (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: 'NoneType' object has no attribute 'getLocaleID')</pre>
</div>
<p>Some sort of Products.CacheSetup related problem on Plone 3.3.x, hiding the real error.
Zope component architecture loading has failed (you are missing critical bits). This is
just the first entry where it tries to use an unloaded code.</p>
<p>Start your instance on the foreground and you should see the actual error.</p>
</div>
<div class="section" id="error-restore-index-when-starting-instance-zeo-server">
<h2><a class="toc-backref" href="#id45">Error _restore_index() when starting instance / ZEO server</a><a class="headerlink" href="#error-restore-index-when-starting-instance-zeo-server" title="Permalink to this headline">Â¶</a></h2>
<p>Example traceback:</p>
<div class="highlight-python"><pre>2011-05-09 09:42:20 INFO ZServer HTTP server started at Mon May  9 09:42:20 2011
        Hostname: 0.0.0.0
        Port: 10997
2011-05-09 09:42:21 INFO Marshall libxml2-python not available. Unable to register libxml2 based marshallers, at least SimpleXMLMarshaller
2011-05-09 09:42:22 INFO DocFinderTab Applied patch version 1.0.4.
Traceback (most recent call last):
  File "/home/moo/code/python2/parts/opt/lib/python2.4/pdb.py", line 1066, in main
    pdb._runscript(mainpyfile)
  File "/home/moo/code/python2/parts/opt/lib/python2.4/pdb.py", line 991, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/home/moo/code/python2/parts/opt/lib/python2.4/bdb.py", line 366, in run
    exec cmd in globals, locals
  File "&lt;string&gt;", line 1, in ?
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/run.py", line 56, in ?
    run()
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/run.py", line 21, in run
    starter.prepare()
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 102, in prepare
    self.startZope()
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/__init__.py", line 278, in startZope
    Zope2.startup()
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/App/startup.py", line 59, in startup
    DB = dbtab.getDatabase('/', is_root=1)
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/datatypes.py", line 280, in getDatabase
    db = factory.open(name, self.databases)
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/datatypes.py", line 178, in open
    DB = self.createDB(database_name, databases)
  File "/home/moo/xxx/parts/zope2/lib/python/Zope2/Startup/datatypes.py", line 175, in createDB
    return ZODBDatabase.open(self, databases)
  File "/home/moo/xxx/parts/zope2/lib/python/ZODB/config.py", line 97, in open
    storage = section.storage.open()
  File "/home/moo/xxx/parts/zope2/lib/python/ZODB/config.py", line 135, in open
    quota=self.config.quota)
  File "/home/moo/xxx/parts/zope2/lib/python/ZODB/FileStorage/FileStorage.py", line 154, in __init__
    r = self._restore_index()
  File "/home/moo/xxx/parts/zope2/lib/python/ZODB/FileStorage/FileStorage.py", line 365, in _restore_index
    index = info.get('index')</pre>
</div>
<p>Reason: Data.fs.index is corrupted.</p>
<p>Fix. Remove Data.fs.index file. The index will be rebuilt on the launch.</p>
</div>
<div class="section" id="importtoolset-typeerror-nonetype-object-is-not-callable">
<h2><a class="toc-backref" href="#id46">importToolset: TypeError: 'NoneType' object is not callable</a><a class="headerlink" href="#importtoolset-typeerror-nonetype-object-is-not-callable" title="Permalink to this headline">Â¶</a></h2>
<p>This happens when you try to install an add-on
product through Add-ons configuration panel.</p>
<p>Traceback:</p>
<div class="highlight-python"><pre>Module ZPublisher.Publish, line 47, in call_object
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 575, in installProducts
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 512, in installProduct
 - __traceback_info__: ('plone.app.registry',)
Module Products.GenericSetup.tool, line 323, in runAllImportStepsFromProfile
 - __traceback_info__: profile-plone.app.registry:default
Module Products.GenericSetup.tool, line 1080, in _runImportStepsFromContext
Module Products.GenericSetup.tool, line 994, in _doRunImportStep
 - __traceback_info__: toolset
Module Products.GenericSetup.tool, line 123, in importToolset</pre>
</div>
<p>You have leftovers from some old add-on installation (persistent tool)
and Python egg code is no longer present for this tool.</p>
<p>You should see a warning in logs giving you a hint when running add-on installer:</p>
<div class="highlight-python"><pre>2011-05-29 16:40:25 INFO GenericSetup.toolset Class Products.Notifica.NotificaTool.NotificaTool not found for tool notifica_tool</pre>
</div>
<p>To fix this, see informatin below (Removing portal tools part)</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.org/documentation/kb/manually-removing-local-persistent-utilities/">http://plone.org/documentation/kb/manually-removing-local-persistent-utilities/</a></li>
</ul>
<p>Example: start site debug shell:</p>
<div class="highlight-python"><pre>bin/instance debug</pre>
</div>
<p>Then run the script for your site id and problem tool id:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">bad_tool</span> <span class="o">=</span> <span class="s">&#39;notifica_tool&#39;</span>
<span class="n">site</span> <span class="o">=</span> <span class="n">app</span><span class="o">.</span><span class="n">yoursiteid</span>

<span class="n">setup_tool</span> <span class="o">=</span> <span class="n">site</span><span class="o">.</span><span class="n">portal_setup</span>
<span class="n">toolset</span> <span class="o">=</span> <span class="n">setup_tool</span><span class="o">.</span><span class="n">getToolsetRegistry</span><span class="p">()</span>
<span class="k">if</span> <span class="n">bad_tool</span> <span class="ow">in</span> <span class="n">toolset</span><span class="o">.</span><span class="n">_required</span><span class="o">.</span><span class="n">keys</span><span class="p">():</span>
    <span class="k">del</span> <span class="n">toolset</span><span class="o">.</span><span class="n">_required</span><span class="p">[</span><span class="n">bad_tool</span><span class="p">]</span>
    <span class="n">setup_tool</span><span class="o">.</span><span class="n">_toolset_registry</span> <span class="o">=</span> <span class="n">toolset</span>
<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&quot;Tool not found:&quot;</span> <span class="o">+</span> <span class="n">bad_tool</span>

<span class="kn">import</span> <span class="nn">transaction</span> <span class="p">;</span> <span class="n">transaction</span><span class="o">.</span><span class="n">commit</span><span class="p">()</span>
<span class="n">app</span><span class="o">.</span><span class="n">_p_jar</span><span class="o">.</span><span class="n">sync</span><span class="p">()</span>
</pre></div>
</div>
<p>In debug shell you can also check what all leftoverts toolset contains:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="gp">&gt;&gt;&gt; </span><span class="n">toolset</span><span class="o">.</span><span class="n">_required</span><span class="o">.</span><span class="n">keys</span><span class="p">()</span>
<span class="go">[&#39;portal_historyidhandler&#39;, &#39;portal_actions&#39;, &#39;portal_skins&#39;, &#39;portal_form_controller&#39;,</span>
<span class="go">&#39;portal_workflow&#39;, &#39;portal_catalog&#39;, &#39;portal_languages&#39;, &#39;kupu_library_tool&#39;, &#39;portal_diff&#39;,</span>
<span class="go">&#39;portal_repository&#39;, &#39;reference_catalog&#39;, &#39;portal_groupdata&#39;, &#39;portal_search_and_replace&#39;,</span>
<span class="go">&#39;portal_atct&#39;, &#39;mimetypes_registry&#39;, &#39;portal_purgepolicy&#39;, &#39;formgen_tool&#39;, &#39;uid_catalog&#39;,</span>
<span class="go">&#39;error_log&#39;, &#39;portal_modifier&#39;, &#39;portal_discussion&#39;, &#39;portal_actionicons&#39;, &#39;portal_calendar&#39;, &#39;portal_metadata&#39;, &#39;portal_url&#39;,</span>
<span class="go">&#39;portal_kss&#39;, &#39;portal_archivist&#39;, &#39;portal_tinymce&#39;, &#39;portal_factory&#39;, &#39;content_type_registry&#39;, &#39;portal_groups&#39;, &#39;portal_controlpanel&#39;,</span>
<span class="go">&#39;portal_uidannotation&#39;, &#39;portal_transforms&#39;, &#39;portal_memberdata&#39;, &#39;portal_javascripts&#39;, &#39;portal_registration&#39;, &#39;portal_css&#39;,</span>
<span class="go">&#39;portal_facets_catalog&#39;, &#39;portal_password_reset&#39;, &#39;plone_utils&#39;, &#39;caching_policy_manager&#39;,</span>
<span class="go">&#39;portal_historiesstorage&#39;, &#39;portal_undo&#39;, &#39;portal_placeful_workflow&#39;, &#39;translation_service&#39;,</span>
<span class="go">&#39;archetype_tool&#39;, &#39;portal_view_customizations&#39;, &#39;portal_syndication&#39;, &#39;portal_quickinstaller&#39;, &#39;portal_uidhandler&#39;,</span>
<span class="go">&#39;portal_referencefactories&#39;, &#39;portal_interface&#39;, &#39;portal_facetednavigation&#39;, &#39;portal_membership&#39;,</span>
<span class="go">&#39;MailHost&#39;, &#39;portal_properties&#39;, &#39;portal_migration&#39;, &#39;portal_types&#39;, &#39;portal_uidgenerator&#39;]</span>
</pre></div>
</div>
<p>More info</p>
<ul class="simple">
<li><a class="reference external" href="http://plone.293351.n2.nabble.com/importToolset-NoneType-object-is-not-callable-upon-product-install-td5553065.html">http://plone.293351.n2.nabble.com/importToolset-NoneType-object-is-not-callable-upon-product-install-td5553065.html</a></li>
</ul>
</div>
<div class="section" id="from-zopeskel-basic-namespace-import-basicnamespace">
<h2><a class="toc-backref" href="#id47">from zopeskel.basic_namespace import BasicNamespace</a><a class="headerlink" href="#from-zopeskel-basic-namespace-import-basicnamespace" title="Permalink to this headline">Â¶</a></h2>
<p>When starting ZopeSkel:</p>
<div class="highlight-python"><pre>File "/home/moo/code/python2/parts/opt/lib/python2.6/pkgutil.py", line 238, in load_module
  mod = imp.load_module(fullname, self.file, self.filename, self.etc)
File "/home/moo/code/plonecommunity/eggs/ZopeSkel-2.19-py2.6.egg/zopeskel/__init__.py", line 2, in &lt;module&gt;
  from zopeskel.basic_namespace import BasicNamespace</pre>
</div>
<p>You were not lucky today:</p>
<div class="highlight-python"><pre>rm -rf /home/moo/code/python2/python-2.6/lib/python2.6/site-packages/ZopeSkel-2.19-py2.6.egg/</pre>
</div>
</div>
<div class="section" id="extensionclass-extensionclass-object-is-not-iterable">
<h2><a class="toc-backref" href="#id48">'ExtensionClass.ExtensionClass' object is not iterable</a><a class="headerlink" href="#extensionclass-extensionclass-object-is-not-iterable" title="Permalink to this headline">Â¶</a></h2>
<p>This error tends to happen after moving a Data.fs to a new instance that does not have the identical add-ons to the original instance.</p>
<p>Traceback:</p>
<div class="highlight-python"><pre>Module ZPublisher.Publish, line 126, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Products.PloneHotfix20110531, line 106, in _patched_bindAndExec
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module App.special_dtml, line 185, in _exec
Module DocumentTemplate.DT_Let, line 77, in render
Module DocumentTemplate.DT_In, line 647, in renderwob
Module DocumentTemplate.DT_In, line 772, in sort_sequence
Module ZODB.Connection, line 860, in setstate
Module ZODB.Connection, line 914, in _setstate
Module ZODB.serialize, line 612, in setGhostState
Module ZODB.serialize, line 605, in getState
Module zope.interface.declarations, line 756, in Provides
Module zope.interface.declarations, line 659, in __init__
Module zope.interface.declarations, line 45, in __init__
Module zope.interface.declarations, line 1382, in _normalizeargs
Module zope.interface.declarations, line 1381, in _normalizeargs
TypeError: ("'ExtensionClass.ExtensionClass' object is not iterable", &lt;function Provides at 0x9f04d84&gt;, (&lt;class 'Products.ATContentTypes.content.folder.ATFolder'&gt;, &lt;class 'Products.Carousel.interfaces.ICarouselFolder'&gt;))</pre>
</div>
<p>In this example traceback the missing add-on is Products.Carousel which provides the marker interface Products.Carousel.interfaces.ICarousel</p>
<p>Solution: Install the missing add-on(s)</p>
</div>
</div>

  </div>

          </div>
        </div>
      </div>
      <div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper">
<p class="logo"><a href="../index.html"><img src="../_static/plone-icon-64.png" />
</a></p>

  <h3><a href="../index.html">Table Of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Exceptions</a><ul>
<li><a class="reference internal" href="#attributeerror-str-object-has-no-attribute-other-mixed-zope-viewpagetemplate-and-five-viewpagetemplate">AttributeError: 'str' object has no attribute 'other' (Mixed zope.viewpagetemplate and Five.viewpagetemplate)</a></li>
<li><a class="reference internal" href="#iteration-over-non-sequence-in-normalizeargs">Iteration over non-sequence in _normalizeargs</a><ul>
<li><a class="reference internal" href="#case-1">Case 1</a></li>
<li><a class="reference internal" href="#case-2">Case 2</a></li>
</ul>
</li>
<li><a class="reference internal" href="#traversalerror-with-lots-of-tuples-and-lists-metal-problem">TraversalError with lots of tuples and lists (METAL problem)</a></li>
<li><a class="reference internal" href="#attributeerror-in-setroles-due-to-workflow-state-transition">AttributeError in setRoles due to workflow state transition</a></li>
<li><a class="reference internal" href="#add-on-installer-error-too-many-values-to-unpack">Add-on installer error: too many values to unpack</a></li>
<li><a class="reference internal" href="#add-on-installer-error-this-object-was-originally-created-by-a-product-that-is-no-longer-installed">Add-on installer error: This object was originally created by a product that is no longer installed</a></li>
<li><a class="reference internal" href="#z3c-form-based-form-updatewidgets-raises-componentlookuperror">z3c.form based form updateWidgets() raises ComponentLookupError</a></li>
<li><a class="reference internal" href="#notfound-error-page-not-found-when-accessing-manage-portlets">NotFound error (Page not found) when accessing &#64;&#64;manage-portlets</a><ul>
<li><a class="reference internal" href="#manually-removing-the-portlet">Manually removing the portlet</a></li>
</ul>
</li>
<li><a class="reference internal" href="#attributeerror-getphysicalpath">AttributeError: getPhysicalPath()</a><ul>
<li><a class="reference internal" href="#demostration">Demostration</a></li>
</ul>
</li>
<li><a class="reference internal" href="#runtimeerror-maximum-recursion-depth-exceeded-archetypes-field-problem">RuntimeError: maximum recursion depth exceeded (Archetypes field problem)</a></li>
<li><a class="reference internal" href="#invalid-or-duplicate-property-id">Invalid or Duplicate property id</a></li>
<li><a class="reference internal" href="#traversalerror-no-traversable-adapter-found">TraversalError: No traversable adapter found</a></li>
<li><a class="reference internal" href="#importerror-inappropriate-file-type-for-dynamic-loading">ImportError: Inappropriate file type for dynamic loading</a></li>
<li><a class="reference internal" href="#badrequest-the-id-xxx-is-invalid-it-is-already-in-use">BadRequest: The id &quot;xxx&quot; is invalid - it is already in use.</a></li>
<li><a class="reference internal" href="#exception-type-name-not-specified-in-createobject">Exception: Type name not specified in createObject</a></li>
<li><a class="reference internal" href="#unauthorized-the-object-is-marked-as-private">Unauthorized: The object is marked as private</a></li>
<li><a class="reference internal" href="#importerror-no-module-named-pil">ImportError: No module named PIL</a></li>
<li><a class="reference internal" href="#notfound-while-accessing-a-browserview-based-view">NotFound while accessing a BrowserView based view</a></li>
<li><a class="reference internal" href="#contentproviderlookuperror-plone-htmlhead">ContentProviderLookupError: plone.htmlhead</a></li>
<li><a class="reference internal" href="#error-while-installing-a-new-portlet-portlets-xml-unbound-prefix">Error while installing a new portlet portlets.xml: unbound prefix</a></li>
<li><a class="reference internal" href="#importerror-couldn-t-import-zpublishereventsbackport">ImportError: Couldn't import ZPublisherEventsBackport</a></li>
<li><a class="reference internal" href="#error-zodb-connection-couldn-t-load-state-for-0x00">ERROR ZODB.Connection Couldn't load state for 0x00</a></li>
<li><a class="reference internal" href="#poskeyerror">POSKeyError</a></li>
<li><a class="reference internal" href="#zope-suddenly-dies-on-osx-without-a-reason">Zope suddenly dies on OSX without a reason</a></li>
<li><a class="reference internal" href="#ioerror-errno-url-error-unknown-url-type-https">IOError: [Errno url error] unknown url type: 'https'</a></li>
<li><a class="reference internal" href="#typeerror-len-of-unsized-object-in-smtplib">TypeError: len() of unsized object in smtplib</a></li>
<li><a class="reference internal" href="#nameerror-name-test-is-not-defined">NameError: name 'test' is not defined</a></li>
<li><a class="reference internal" href="#traversalerror-subject-name-in-expressions">TraversalError(subject, name) in expressions</a></li>
<li><a class="reference internal" href="#content-status-history-won-t-render-traceback-is-content-path-reversed">Content status history won't render - traceback is content path reversed</a></li>
<li><a class="reference internal" href="#attributeerror-module-object-has-no-attribute-httpsconnection">AttributeError: 'module' object has no attribute 'HTTPSConnection'</a></li>
<li><a class="reference internal" href="#linguaplone-importerror-cannot-import-name-permissions">LinguaPlone: ImportError: cannot import name permissions</a></li>
<li><a class="reference internal" href="#typeerror-nonetype-object-is-not-callable">TypeError: 'NoneType' object is not callable</a></li>
<li><a class="reference internal" href="#importerror-no-module-named-pkgutil">ImportError: No module named pkgutil</a></li>
<li><a class="reference internal" href="#picklingerror-can-t-pickle-class-collective-singing-async-iqueue-import-of-module-collective-singing-async">&quot;PicklingError: Can't pickle &lt;class 'collective.singing.async.IQueue'&gt;: import of module collective.singing.async&quot;</a></li>
<li><a class="reference internal" href="#system-lxml-too-old">System lxml too old</a></li>
<li><a class="reference internal" href="#traversalerror-standard-macros">TraversalError: &#64;&#64;standard_macros</a></li>
<li><a class="reference internal" href="#attributeerror-wrapper-descriptor-object-has-no-attribute-im-func">AttributeError: 'wrapper_descriptor' object has no attribute 'im_func'</a></li>
<li><a class="reference internal" href="#getutility-fails-componentlookuperror">getUtility() fails: ComponentLookupError</a></li>
<li><a class="reference internal" href="#attributeerror-request-in-getobject">AttributeError: REQUEST in getObject</a></li>
<li><a class="reference internal" href="#get-language-nonetype-object-has-no-attribute-getlocaleid">get_language: 'NoneType' object has no attribute 'getLocaleID'</a></li>
<li><a class="reference internal" href="#error-restore-index-when-starting-instance-zeo-server">Error _restore_index() when starting instance / ZEO server</a></li>
<li><a class="reference internal" href="#importtoolset-typeerror-nonetype-object-is-not-callable">importToolset: TypeError: 'NoneType' object is not callable</a></li>
<li><a class="reference internal" href="#from-zopeskel-basic-namespace-import-basicnamespace">from zopeskel.basic_namespace import BasicNamespace</a></li>
<li><a class="reference internal" href="#extensionclass-extensionclass-object-is-not-iterable">'ExtensionClass.ExtensionClass' object is not iterable</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="unicode.html"
                        title="previous chapter">Unicode encoding and decoding</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="images.html"
                        title="next chapter">Image troubleshooting</a></p>
  <h3>This Page</h3>
  <ul class="this-page-menu">
    <li><a href="../_sources/troubleshooting/exceptions.txt"
           rel="nofollow">Show Source</a></li>
  </ul>
<div id="searchbox" style="display: none">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" size="18" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="images.html" title="Image troubleshooting"
             >next</a> |</li>
        <li class="right" >
          <a href="unicode.html" title="Unicode encoding and decoding"
             >previous</a> |</li>
        <li><a href="../index.html">Plone Community Managed Developer Manual v1.0 documentation</a> &raquo;</li>
          <li><a href="index.html" >Troubleshooting</a> &raquo;</li> 
      </ul>
    </div>

    <div class="footer">
        &copy; Copyright 2010 mFabrik Research Oy and Plone community contributors.
      Created using <a href="http://sphinx.pocoo.org/">Sphinx</a> 1.0.4.
    </div>


  </body>
</html>